### ISSUE TITLE
Delivery Quests

### ISSUE THREAD

**Issue by Amalissia** [PikaMug/Quests#1771] opened 2021-08-15 13:46 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.6
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Make a citizen -  try to get a stage to deliver items to the citizen ( I tried 5 salmon- 1 honey bottle) 

-- it wont let me press "done"  it will repeatedly go back to the page i'm on and I cant exit out till I've cleared the parameters

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Sorry I cant I've deleted the delivery quest so it doesnt show up in the quests area.

**Comment by Amalissia** [comment] 2021-08-15 13:47
It may be a me problem where I've forgotten or didnt know to do one thing.

**Comment by DeadlykillOfficial** [comment] 2021-08-15 13:48
This is not a bug. But instead you are doing it wrong when you add 2 items to deliver you must add 2 npcs and 2 messages. The error you are getting its "all lists must have same amount of entries"

**Comment by Amalissia** [comment] 2021-08-15 13:52
D: well drat I was gonn hve them deliver honey and fish to a bear  --- maybe it can be an added feature in the future

**Comment by DeadlykillOfficial** [comment] 2021-08-15 13:57
I don't understand what you mean by feature?

**Comment by DeadlykillOfficial** [comment] 2021-08-15 13:59
You can still deliver whatever you want to whoever you want. You are just not filling the lists and Syntax properly Therefor it doesn't let you continue

**Comment by Amalissia** [comment] 2021-08-15 14:02
So if i want 2 items delivered to the same NPC on the Same quest do i need two stages?

**Comment by DeadlykillOfficial** [comment] 2021-08-15 14:03
No? You just type 2 times same ID. For example you have 2 items then you do NPC "1 1"
It would add 2 times NPC id 1
And then you should read info how to split the message into two.

**Comment by DeadlykillOfficial** [comment] 2021-08-15 14:03
Dm me in discord

**Comment by Amalissia** [comment] 2021-08-15 14:10
I couldnt find a discord >< thats why i'm here but i think i understand what you mean-

**Comment by DeadlykillOfficial** [comment] 2021-08-15 14:14
https://discordapp.com/invite/QdJAv2G7qg

**Comment by PikaMug** [comment] 2021-08-16 00:11
I assume this has been resolved via Discord.

**Closed by PikaMug** 2021-08-16 00:11 UTC
Labels: bug
