### ISSUE TITLE
Ability to use Multiple block types to reach requirement goal

### ISSUE THREAD

**Issue by Varadic** [PikaMug/Quests#1978] opened 2022-06-22 22:57 UTC
### What does your feature do?

At the moment, Quests allows you to add multiple break block types, but not the ability to combined those break block types to reach the total amount of ores required. 

At the moment, the setup below represents a quest to break 5 coal ore blocks. 

          break-block-names:
          - COAL_ORE
          break-block-amounts:
          - 5
          
This next line shows how at the moment, you have to break 5 coal ore blocks, as well as 5 deepslate coal ore blocks

          break-block-names:
          - COAL_ORE
          - DEEPSLATE_COAL_ORE
          break-block-amounts:
          - 5
          - 5
          

### How would people use it?

Pretty much my suggestion is to add the ability that if the brea-block-amounts only show one line instead of 2, then the two break-blocks required will combined the equal total, meaning that You can break either 5 coal ore, 5 deepslate coal ore, or a mixture of both to equal 5. (say like 2 coal ore, and 3 deepslate coal ore for example)

Which would be especially useful since there are two different types of each ore now.

**Comment by PikaMug** [comment] 2022-06-23 12:47
Duplicate of #789

Note that a third-party module exists for this https://lectern.browsit.org/resources/resource/19/

**Closed by PikaMug** 2022-06-23 12:47 UTC
Labels: enhancement
