### ISSUE TITLE
Quests When Completed with Parties Plugin Causing Multiple Completions

### ISSUE THREAD

**Issue by polsonator2** [PikaMug/Quests#1001] opened 2019-11-13 05:50 UTC
Version: Questss V3.8.2
https://ci.codemc.io/job/PikaMug/job/Quests/46/

Quest Example
[AG0RL4vq.txt](https://github.com/PikaMug/Quests/files/3839572/AG0RL4vq.txt)

I am now seeing a bug when using the Parties Plugin with Quests v 3.8.2.   When a party of individuals finishes a quest together, instead of completing the quest once and receiving the rewards once, they automatically complete the quest multiple times over and over, maybe like 40 or 50 times.  This causes the SkillAPI reward of XP (stated in my quest sample) to max out at 9999 since the quest completed so many times, even though the reward should be once at 50.  Here is the parties plugin that I am using and this is one that was recommended on the Quests webpage to be used:

https://www.spigotmc.org/resources/parties-an-advanced-parties-manager.3709/

The bug did not appear to affect a single player in a party or players that were not in a party.  Party version used was 2.6.8.  The bug does not appear in Quests version 3.7.8, which is what I have reverted back to unless this can be fixed  

Polsonator2

**Comment by AlessioDP** [comment] 2019-11-13 11:38
Should be fixed with #1002 

The problem is related to any quest that have multiplayer level set to 4 ;)

**Comment by PikaMug** [comment] 2019-11-14 03:30
@AlessioDP Thanks for the quick fix! 

@polsonator2 Give the following dev build a try. If you're using QuestsGUI, recent changes to the API may cause conflicts. Worst case, uninstall QuestsGUI until the next Spigot release.
https://ci.codemc.io/job/PikaMug/job/Quests/47/

**Closed** 2019-11-14 03:30 UTC
Labels: bug
