### ISSUE TITLE
Click on the messages instead of typing the number

### ISSUE THREAD

**Issue by Skyfighter1** [PikaMug/Quests#806] opened 2019-05-26 11:21 UTC
**What does your feature do?**
It would be nice if you could support clickabled messages.  It would be easier for creators and players.
**How would people use it?**
Peolpe can click on the messages instead of typing the number.

**Comment by PikaMug** [comment] 2019-05-26 22:22
Duplicate of #618

**Closed by PikaMug** 2019-05-26 22:22 UTC
