### ISSUE TITLE
[Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v3.6.5-b717

### ISSUE THREAD

**Issue by baolam0000** [PikaMug/Quests#768] opened 2019-04-13 00:23 UTC
[Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v3.6.5-b717
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-f09662d-7c395d4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot.jar:git-Spigot-f09662d-7c395d4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot.jar:git-Spigot-f09662d-7c395d4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:945) ~[spigot.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[spigot.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot.jar:git-Spigot-f09662d-7c395d4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-f09662d-7c395d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:797) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot.jar:git-Spigot-f09662d-7c395d4]
	... 15 more

**Comment by PikaMug** [comment] 2019-04-13 04:34
Duplicate of #763 

Use the latest dev build.

**Closed by PikaMug** 2019-04-13 04:34 UTC

**Comment by baolam0000** [comment] 2019-04-13 14:21
Where i can fidn the dev build

**Comment by PikaMug** [comment] 2019-04-13 21:45
http://ci.ac3-servers.eu/job/Quests/
