### ISSUE TITLE
Console getting spammed with errors (no added quests, some config options changed but more or less unaltered default state)

### ISSUE THREAD

**Issue by 99leo** [PikaMug/Quests#1509] opened 2020-12-16 19:52 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0-rc3
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Install quests on 1.16.4
errors: https://pastebin.com/dVFUL7w4
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
config: https://pastebin.com/XNSivKji
quests: https://pastebin.com/RMYrvX4C

**Comment by PikaMug** [comment] 2020-12-16 22:52
Duplicate of #1483 

Use latest development build https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-12-16 22:52 UTC
Labels: bug
