### ISSUE TITLE
Hi The Guy From QAV Vehicle Bug With objectives location.

### ISSUE THREAD

**Issue by Prowco** [PikaMug/Quests#947] opened 2019-09-28 07:50 UTC
Hi buddy i dont know if you remember me:
https://github.com/PikaMug/Quests/issues/929

Well the plugin developer of quality armory awnser this:

**Because QAV uses armorstands for the player to drive, PlayerMoveEvent is not called. If the player is in a vehicle, you would most likely need to create a runnable to listen every couple of seconds to see if they moved to the right location.**

So you think you can make something for make quest compabilty with vehicles you know the plugin detects when you reach a location inside the vehicle.?
Thanks for all the help.

**Comment by PikaMug** [comment] 2019-09-30 00:36
Original issue is #924 
Developer response is from https://github.com/ZombieStriker/QualityArmory/issues/41

@Prowco I'll have to see about creating a separate bridge plugin for your use case. This will take some time. I'll keep this ticket updated with any progress.

**Comment by Prowco** [comment] 2019-09-30 02:04
Thanks

**Comment by PikaMug** [comment] 2019-11-11 19:09
Rather than create a separate bridge plugin - one for QAV and then every other plugin that follows - I've added a config option that will enable additional player tracking within Quests. Once the new version is installed and run, you will see the following config.yml option:

`strict-player-movement: 0`

The '0' means disabled. If we set the option to '3' this will enable checking the player's location every 3 seconds and update reach-location objectives accordingly. Note that setting the option closer to zero improves accuracy, but sacrifices server performance. You will likely want to adjust this to best fit your server's needs.

Use the following dev build, considered highly experimental:
https://ci.codemc.io/job/PikaMug/job/Quests/45/

**Comment by Prowco** [comment] 2019-11-11 19:12
Perfect thank you so much i goin to test

**Comment by Prowco** [comment] 2019-11-11 20:47
and i try add the option to config by myself but its not working quests continue not detecting when i reach the location inside a vehicle

**Comment by PikaMug** [comment] 2019-11-12 03:12
It should have populated automatically, but I'm glad you were able to add it yourself. Make sure to set the value to something greater than '0' or it won't work.

**Comment by Prowco** [comment] 2019-11-12 15:39
Well i try with 1 then with 2 and last with 3 but its continue not working i need get out of the vehicle if i want quests detect i reach the location i cant inside the vehicle
Here i record a video so you can see its not working
https://www.dropbox.com/h?preview=Not+Working.flv

**Comment by PikaMug** [comment] 2019-11-14 07:44
Would you mind posting your config.yml so I can make sure it looks correct?

Also, what is your name in the Discord group?

**Comment by Prowco** [comment] 2019-11-14 13:31
Wesley#5411 which group?
Yeah here is my config

> accept-timeout: 20
> allow-command-questing: true
> allow-command-quests-with-npcs: false
> allow-quitting: true
> ask-confirmation: true
> generate-files-on-join: true
> ignore-locked-quests: false
> kill-delay: 600
> language: en-US
> max-quests: 0
> show-requirements: true
> show-titles: true
> translate-names: true
> translate-subcommands: false
> use-compass: true
> strict-player-movement: 2
> npc-effects:
>   enabled: true
>   new-quest: note
>   redo-quest: angry_villager

**Comment by PikaMug** [comment] 2019-11-14 19:44
Config looks correct. I'm speaking of the official Quests group:
https://discordapp.com/invite/d56CQ6e

I'll try reaching out to you regarding this issue.

**Comment by Prowco** [comment] 2019-11-14 23:12
Ok my name is Wesley on discord

**Comment by PikaMug** [comment] 2019-11-15 01:26
Resolved via Discord. OP may have downloaded an old or invalid build of Quests. Both parties confirmed that the fix is working as intended with the latest Jenkins build.

**Closed by PikaMug** 2019-11-15 01:26 UTC
Labels: enhancement
