### ISSUE TITLE
npc 

### ISSUE THREAD

**Issue by pookylish** [PikaMug/Quests#1090] opened 2020-02-22 20:46 UTC
hello i am running a paper 1.14.4 server and i am having trouble on quest version 3.8.7 where i create a npc start quest and when i have fished setting up the quest i click on the npc to open up what quests they have and a gui opens with the quests inside i then try and click on the quest and it says in chat that i need to speak with the npc to start this quest but the only thing that comes up is the gui and that it i cant start the quest

**Comment by Flexiboi** [comment] 2020-02-22 21:29
I do have the same problem on my 1.15 server.
Even after removeing the files, redownloading it and staring from 0.

**Comment by PikaMug** [comment] 2020-02-22 23:57
Duplicate of #1081 

Use latest dev build from https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-02-22 23:57 UTC
Labels: bug

**Comment by Kangaroo942** [comment] 2020-02-23 13:59
I had the same problem, but version 3.8.8 fixed it.
Thanks
