### ISSUE TITLE
Quest Progress Bug

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#1947] opened 2022-05-04 09:54 UTC
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.4.0-b328
Paper version: 1.18.2

### Describe the problem and how to replicate it.

Hello, I'm having some weird issue with quest, some players been saying there "quests progress" resets back sometime. It's been strangely happening recently. Players seem to be losing quest progress which that needs fixing asap.

### Any console errors to share?

```shell
No console error.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Here's the quests.yml -> https://www.toptal.com/developers/hastebin/guzabipuna.yaml
```

**Comment by PikaMug** [comment] 2022-05-04 10:20
Can you provide more details? What is the nature of the progress lost? Any particular quests affected? Were the players online at the time? Did you run any commands which might have affected this? Are you using YAML or MySQL storage?

**Comment by AccioAce** [comment] 2022-05-04 21:14
> Can you provide more details? What is the nature of the progress lost? Any particular quests affected? Were the players online at the time? Did you run any commands which might have affected this? Are you using YAML or MySQL storage?

Hello, so the nature of the progress lost is when players does the quests like for example breeding, mining, etc it resets their progress back and they have to do it over all again. I'm not sure which particular quests is affected, there could be multiple it seems. Yeah the players were online at that time I believe but we did had server restart but that shouldn't had affect it. I did not run any quests command beside sometime "/save-all" when is needed. So none of the related quests commands. I'm not using YAML or any MySQL storages for quests.

**Comment by AccioAce** [comment] 2022-05-04 21:59
A player said: "It didn't completely rollback. It just rollback to a certain point. It rolledback to the same point twice." 
Another player said: "I've had a lot of my quest progress rolled back.  I had the nether trees done, copper ore, iron ore done.  Some ghast deaths and other progress is also gone, back to zero, or not the correct counts.  I don't have a screenshot of my progress the last time I logged off, but I do have the materials I harvested that shows no progress."

**Comment by PikaMug** [comment] 2022-05-05 03:43
> I'm not using YAML or any MySQL storages for quests.

You must be using one or the other. Please check the `storage-method.player-data` node in the _config.yml_ file.

Thanks for that information. May I ask why you use the /save-all command?

**Comment by AccioAce** [comment] 2022-05-05 06:07
> > I'm not using YAML or any MySQL storages for quests.
> 
> You must be using one or the other. Please check the `storage-method.player-data` node in the _config.yml_ file.
> 
> Thanks for that information. May I ask why you use the /save-all command?

Hello, ah I see here what I find.
storage-method:
  player-data: yaml

Will you be fixing this bug on the next update build? And as for "/save-all" just what I do sometime to make sure everything saved. Lol

**Comment by PikaMug** [comment] 2022-05-05 07:58
This bug will be fixed once it can be reliably replicated.

Just to clarify, /save-all is a Bukkit command which does not save any Quests-related data. I'd recommend you set `ticks-per.autosave` in _bukkit.yml_ to something like 6000 instead of using that command.

**Comment by hkkongou** [comment] 2022-05-05 11:38
> > > I'm not using YAML or any MySQL storages for quests.
> > 
> > 
> > You must be using one or the other. Please check the `storage-method.player-data` node in the _config.yml_ file.
> > Thanks for that information. May I ask why you use the /save-all command?
> 
> Hello, ah I see here what I find. storage-method: player-data: yaml
> 
> Will you be fixing this bug on the next update build? And as for "/save-all" just what I do sometime to make sure everything saved. Lol

I have such problem 1 year ago and I switched to MySQL later on until now. However I am not sure whether it happen on my server now.

My recommendation is that you can backup your YAML storage data once a day, or for some period, if the data loss occurs, send the backup version and loss version of the player's YAML files here so that @PikaMug can have some diagnostic , that's how I did last year  #1589 

some side track here, last year I found out that if I got quests.compass (?) permission (or another one, is too old for me to remember) remove from a player, the player's data cannot be saved, the reason why I removed is because I have a player jailed so I set luck perms * deny permission to that player.

**Comment by AccioAce** [comment] 2022-05-05 18:07
> This bug will be fixed once it can be reliably replicated.
> 
> Just to clarify, /save-all is a Bukkit command which does not save any Quests-related data. I'd recommend you set `ticks-per.autosave` in _bukkit.yml_ to something like 6000 instead of using that command.

ah I see, thanks for the suggestion about the bukkit command. Oh you couldn't figure out the issue and currently waiting for someone to help fix it?

**Comment by MarxminSD** [comment] 2022-05-15 08:20
I unfortunately don't know what I could contribute to help pinpoint the cause of this bug, but I am having the same issue. I've experienced it randomly happening, but noticed earlier today I created a new quest, then ran /quests top before reloading. I ran /qa reload, then checked /quests top, and some player data was definitely deleted.
![image](https://user-images.githubusercontent.com/96161173/168463756-e8f5127e-6e64-4069-b4a6-d95a3097bbdc.png)

**Comment by PikaMug** [comment] 2022-05-15 12:25
@MarxminSD What was the change you made in editor before running _/questadmin reload_?

**Comment by AccioAce** [comment] 2022-05-17 19:34
Hello @PikaMug Mind me ask if there any updates for this?

**Comment by MarxminSD** [comment] 2022-05-17 19:41
> @MarxminSD What was the change you made in editor before running _/questadmin reload_?

@PikaMug I created a new quest - specifically, it was to go to a location, then turn in 64 torches and 3 iron pickaxes to an NPC.

**Comment by PikaMug** [comment] 2022-05-17 23:00
@AccioAce The file you originally linked is empty. Please use a site which won't expire.

@MarxminSD Do you have any modules installed?

**Comment by MarxminSD** [comment] 2022-05-17 23:40
@PikaMug Nope - no modules!

**Comment by MrGrOGC** [comment] 2022-05-25 14:01
Hello there ! Same problem for me, after each restart of my server. All progression is lost. Actually, I don't have any players because the server is not open yet, but I hope you find a way to fix it 😬 
I send you [my quests](https://pastebin.com/nh4Z5VCY) and I don't use database, but it's coming

**Comment by sebberj** [comment] 2022-07-01 23:05
I got the same problem. Im not sure if i found the cause of the problem, but i made a Farmer Quest where you need to break 64 Wheat and if you break 32 and place 10 wheat seed, the broken wheat progress goes to 22.. ?

**Comment by sebberj** [comment] 2022-07-03 22:18
I got the same problem. I am not sure if i found the cause of the problem.

I created a Farmer Quest on my servere. The Quest requires that you will need to break 64 wheat to complete the Quest. But if a player has broken 30/64 Wheat, andplace 10 wheat seeds later, the progress bar turns to 20/64. So i think the problem is that when you're placing seeds its attracting the placed Seeds with the broken Wheat .. ? Make sense?

My Quest:
` Farmer1:
    name: 'Farmer Quest #1'
    ask-message: ''
    finish-message: §bGodt klaret! - §aHer er din belønning
    stages:
      ordered:
        '1':
          break-block-names:
          - WHEAT
          break-block-amounts:
          - 64
          break-block-durability:
          - 0
    rewards:
      money: 500
      commands:
      - addxp <player> Herbalism 1000
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      require-same-quest: true`

**Comment by PikaMug** [comment] 2022-07-03 22:34
@sebberj Your comment is marked as off-topic as the issue you're describing is unrelated (and decrementing progress for replaced blocks is an intentional feature). If you have any further questions, create your own ticket.

**Comment by PikaMug** [comment] 2022-07-30 13:25
Potentially useful stacktrace for potential contributors:
https://pastebin.com/YiBwrZ2j

**Comment by PikaMug** [comment] 2022-09-01 01:35
I've made another attempt at fixing this. You may notice server shutdown and _/questadmin_ take slightly longer to execute, especially with a larger player count.

https://ci.codemc.io/job/PikaMug/job/Quests/360/

**Closed** 2022-09-27 06:47 UTC
Labels: bug

**Comment by AccioAce** [comment] 2022-10-22 00:34
Hello @PikaMug had this actually been resolved and fixed?

**Comment by PikaMug** [comment] 2022-10-22 03:11
It would seem so, as there haven't been any reports to the contrary. If you or anyone else experience data loss, please open a new issue.
