### ISSUE TITLE
Bug with quest requirements

### ISSUE THREAD

**Issue by lubaskinc0de** [PikaMug/Quests#2139] opened 2023-08-18 16:07 UTC
### What is your Quests version / build number (do *not* say "latest")?

4.8.3-b423

### Describe the problem and how to replicate it.

%quests_player_has_completed_quest_Красные грибы% == true

### Any console errors to share?

```shell
[19:00:04 WARN]: me.blackvein.quests.exceptions.QuestFormatException: Requirement quests has unknown quest ID custom2, manually update it to a valid ID, see quest of ID custom15
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:2418)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuests(Quests.java:1972)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.lambda$reload$4(Quests.java:1905)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:00:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:00:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[19:00:04 WARN]: me.blackvein.quests.exceptions.QuestFormatException: Requirement quests has unknown quest ID custom15, manually update it to a valid ID, see quest of ID custom16
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:2418)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuests(Quests.java:1972)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.lambda$reload$4(Quests.java:1905)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:00:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:00:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[19:00:04 WARN]: me.blackvein.quests.exceptions.QuestFormatException: Requirement quests has unknown quest ID custom16, manually update it to a valid ID, see quest of ID custom17
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:2418)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuests(Quests.java:1972)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.lambda$reload$4(Quests.java:1905)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:00:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:00:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[19:00:04 WARN]: me.blackvein.quests.exceptions.QuestFormatException: Requirement quests has unknown quest ID custom17, manually update it to a valid ID, see quest of ID custom18
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:2418)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuests(Quests.java:1972)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.lambda$reload$4(Quests.java:1905)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:00:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:00:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[19:00:04 WARN]: me.blackvein.quests.exceptions.QuestFormatException: Requirement quests has unknown quest ID custom18, manually update it to a valid ID, see quest of ID custom19
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:2418)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuests(Quests.java:1972)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.lambda$reload$4(Quests.java:1905)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:00:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:00:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[19:00:04 WARN]: me.blackvein.quests.exceptions.QuestFormatException: Requirement quests has unknown quest ID custom19, manually update it to a valid ID, see quest of ID custom20
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:2418)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuests(Quests.java:1972)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.lambda$reload$4(Quests.java:1905)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:00:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:00:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[19:00:04 WARN]: me.blackvein.quests.exceptions.QuestFormatException: Requirement quests has unknown quest ID custom20, manually update it to a valid ID, see quest of ID custom21
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:2418)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.loadQuests(Quests.java:1972)
[19:00:04 WARN]:        at Quests-4.8.3.jar//me.blackvein.quests.Quests.lambda$reload$4(Quests.java:1905)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:00:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:00:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:00:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:00:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[19:00:04 WARN]: [Quests] Unable to consider custom objectives because quest for custom15 was null
[19:00:04 WARN]: [Quests] Unable to consider custom objectives because quest for custom16 was null
[19:00:04 WARN]: [Quests] Unable to consider custom objectives because quest for custom17 was null
[19:00:04 WARN]: [Quests] Unable to consider custom objectives because quest for custom18 was null
[19:00:04 WARN]: [Quests] Unable to consider custom objectives because quest for custom19 was null
[19:00:04 WARN]: [Quests] Unable to consider custom objectives because quest for custom20 was null
[19:00:04 WARN]: [Quests] Unable to consider custom objectives because quest for custom21 was null
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom15:
    name: Основы Алхимии | Часть 1
    ask-message: Привет Странник! Впечатляет что ты нашел меня! Ну а теперь! Я научу
      тебя основам алхимии, я щедро награждаю тех кто идет по моему пути, ни слова
      больше!
    finish-message: Так держать! Дальше мы изучим новые виды зелий!
    npc-giver-uuid: 307d27e8-53b5-47bc-86dd-be02136f1bf3
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: POTION
      meta:
        ==: ItemMeta
        meta-type: POTION
        potion-type: minecraft:strong_swiftness
    requirements:
      quests:
      - custom2
    stages:
      ordered:
        '1':
          items-to-brew:
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          start-message: Итак, для того чтобы сварить зелье скорости 2 уровня, тебе
            необходимо для начала сварить мутное зелье с помощью адского нароста!
            А потом с помощью сахара сварить зелье скорости! И улучшить его до 2 уровня
            с помощью светопыли!
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:strong_swiftness
          npc-delivery-uuids:
          - 307d27e8-53b5-47bc-86dd-be02136f1bf3
          - 307d27e8-53b5-47bc-86dd-be02136f1bf3
          - 307d27e8-53b5-47bc-86dd-be02136f1bf3
          - 307d27e8-53b5-47bc-86dd-be02136f1bf3
          - 307d27e8-53b5-47bc-86dd-be02136f1bf3
          delivery-messages:
          - Спасибо. Осталось всего <amount>!
          - Спасибо. Осталось всего <amount>!
          - Спасибо. Осталось всего <amount>!
          - Спасибо. Осталось всего <amount>!
          - Спасибо. Осталось всего <amount>!
          start-message: Теперь доставь мне то, что ты сварил!
    rewards:
      money: 3000
      exp: 300
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true


custom2:
    name: Шаг Свиньи
    ask-message: Привет друг мой! В завершении нашего адского путешествия, я бы хотел
      устроить пир! Но какой-же пир, проходит без музыки? Музыку стоит подобрать тематическую,
      я слышал что где-то в развалинах бастиона, есть интересная пластинка....
    finish-message: Вот и закончилось наше путешествие, спасибо друг!
    npc-giver-uuid: ad71fecc-3028-4d8b-871d-983105fb5cb7
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: MUSIC_DISC_PIGSTEP
    requirements:
      quests:
      - custom14
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: MUSIC_DISC_PIGSTEP
          npc-delivery-uuids:
          - ad71fecc-3028-4d8b-871d-983105fb5cb7
          delivery-messages:
          - Спасибо. Осталось всего <amount>!
    rewards:
      money: 5000
      exp: 500
      commands:
      - lp user <player> permission set interactions.start.fire_lord_quest
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

**Comment by PikaMug** [comment] 2023-08-18 21:25
Duplicate of #2131

**Closed by PikaMug** 2023-08-18 21:25 UTC
Labels: bug
