### ISSUE TITLE
planner options for in game time

### ISSUE THREAD

**Issue by KingofAnomaly** [PikaMug/Quests#1989] opened 2022-07-14 13:59 UTC
### What does your feature do?

The ability to plan quests based on in game time.

### How would people use it?

quests could be only available during a certain time of the Minecraft day or at night. small quests to hunt mobs at night or to kill a specific number of mobs in one night. This could be used to give quests more of an rpg feel.

**Comment by PikaMug** [comment] 2022-07-15 05:10
Duplicate of #1634

**Closed by PikaMug** 2022-07-15 05:10 UTC
Labels: enhancement
