### ISSUE TITLE
Quests notify player when they are off cooldown

### ISSUE THREAD

**Issue by Nericu** [PikaMug/Quests#815] opened 2019-05-31 23:44 UTC
**What would this feature do? **
If a player logs in and a quest that normally has a cool down comes up it will notify them via chat that particular quest is off cool down (or all of them if its multiple.)
     - could be a written book that appears in their inventory (space permitting) with a list of quests off cool-down (not just do-able but off cool-down specifically) and a notification in chat.

**How would people use it?**
They would use it to know when a quest is do-able again.

**Comment by PikaMug** [comment] 2019-06-01 03:08
Duplicate of #633

**Closed by PikaMug** 2019-06-01 03:08 UTC
