### ISSUE TITLE
Error console spam

### ISSUE THREAD

**Issue by t0xic1** [PikaMug/Quests#745] opened 2019-03-20 23:45 UTC
Spams this error furiously

Quests version 3.6.4

https://pastebin.com/eZqnRJW6

Didnt modify any files nor creating anything new just started spamming today on console. (havent added new plugins either)

**Comment by PikaMug** [comment] 2019-03-21 15:50
Duplicate of #743 

Use the latest dev version from http://ci.ac3-servers.eu/job/Quests/

**Closed by PikaMug** 2019-03-21 15:50 UTC
