### ISSUE TITLE
2nd Quests requires an other quest

### ISSUE THREAD

**Issue by Troublemaker141** [PikaMug/Quests#2087] opened 2023-04-02 10:40 UTC
### What is your Quests version / build number (do *not* say "latest")?

4.8.0

### Describe the problem and how to replicate it.

Setting up 2 standart quest (used Iron Miner and Catch Fish) with start NPC.
I can finish the first quest without problems, but the second quest always requires the quest i have done.
![questbug](https://user-images.githubusercontent.com/66125147/229347903-b6944cbe-1666-487c-ba1d-18dd4a484e77.PNG)

It happens on a clean reinstall too, we use it with citizen,

### Any console errors to share?

```shell
No
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Iron Miner and Catch Fish, but other custom quests do the same.
```

**Comment by PikaMug** [comment] 2023-04-02 15:11
Duplicate of #2083 

Use https://ci.codemc.io/job/PikaMug/job/Quests/402/

**Closed** 2023-04-02 15:11 UTC
Labels: bug
