### ISSUE TITLE
Restore previous quest editor session

### ISSUE THREAD

**Issue by marvinjasper** [PikaMug/Quests#1124] opened 2020-03-15 13:52 UTC
**What does your feature do?**
If you are disconnected while in the quest editor, pending changes will be saved until you reconnect. Currently, disconnecting means that pending changes are lost.

Unintentional disconnection shouldn't be very common, so that might limit the usefulness of this feature.

**How would people use it?**
When you reconnect and attempt to open the quests editor again after being disconnected, you will be prompted as to whether you want to restore the previous session of the quest editor where you left off, or abandon those changes and start a new session.

**Comment by PikaMug** [comment] 2020-03-18 06:17
Duplicate of #1088 

I'm having trouble seeing much value in this. Although I appreciate users putting effort into their quests, there isn't any part of the plugin that requires complicated input or intricate setup. What would take so long that autosave could actually be useful?

**Comment by marvinjasper** [comment] 2020-03-18 18:32
When I'm guiding someone less familiar with the plugin through the quest editor and/or working on a quest with them, it might take a few hours. And yes, we're paranoid enough to go back to the main menu of the quest editor and save every now and then. :)

Fortunately, anyone working in the quest editor has a permission which makes them exempt from being kicked for being AFK, because that would be silly, wouldn't it.

Even being able to save and continue working would be a great help.

**Comment by PikaMug** [comment] 2020-03-19 00:32
Thanks for your reply. I understand that, as with any plugin, there is a learning curve to overcome. However, I'm still having trouble comprehending how a single quest would take a few hours to set up. What part of the process would you say is most time-consuming for your pupils?

**Comment by marvinjasper** [comment] 2020-03-19 01:37
The biggest stumble for them last time, I would say, was remembering that Complete messages and Finish Actions trigger after a stage's objective is completed. Objective display override also took some explaining. This would only be the second quest that they were working on, and it was pretty ambitious stuff, a welcome tour around a city's points of interest with some talking to NPCs.

Quite a few times, they asked me to check their work, so they saved and exited the quest editor, I hopped into the quest editor, and sure enough, there were a few places where things needed changing, so I handed it back to them with some clearer guidance.

So yes, a few hours is probably how much time went by. I'd say it's a combination of jumping in at the deep end and not having much prior experience of anything like Quests. On the other hand, this group does pay attention and take notes. By the time I needed to log off, they were confident enough to finish the quest without me.

**Comment by PikaMug** [comment] 2020-07-18 05:05
Ask- and complete-messages are now populated with generic values and the objective display override has been renamed for clarification. So long as at least one Stage has been created, the quest may be saved at any time. Although I am not opposed to an auto-save function, I've settled on the mindset that making quests easier/quicker to create is the ideal solution here.

**Closed by PikaMug** 2020-07-18 05:05 UTC
Labels: duplicate, enhancement
