### ISSUE TITLE
[BUG] Reload not working

### ISSUE THREAD

**Issue by jurajplayercze** [PikaMug/Quests#1733] opened 2021-07-01 11:10 UTC
When we try to reload quests, it send error. Using version 4.0.5 b246

[13:06:33] [Server thread/INFO]: JuraJ_Player issued server command: /quest reload
[13:06:42] [Server thread/INFO]: JuraJ_Player issued server command: /quests:questadmin reload
[13:06:42] [Craft Scheduler Thread - 760/INFO]: [Quests] Loaded language cs-CZ. Translations via Crowdin
[13:06:42] [Craft Scheduler Thread - 760/WARN]: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:1795)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1004)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at me.blackvein.quests.Quest.updateCompass(Quest.java:339)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at me.blackvein.quests.Quester.checkQuest(Quester.java:3832)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at me.blackvein.quests.Quests$3.run(Quests.java:1614)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[13:06:42] [Craft Scheduler Thread - 760/WARN]: at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by PikaMug** [comment] 2021-07-01 11:21
Duplicate of #1729

https://ci.codemc.io/job/PikaMug/job/Quests/247/

**Closed by PikaMug** 2021-07-01 11:21 UTC
Labels: bug
