### ISSUE TITLE
Hi the Quality Armor V Guy.

### ISSUE THREAD

**Issue by Prowco** [PikaMug/Quests#929] opened 2019-08-29 04:44 UTC
**What does your feature do?**
Can u add me in discord please hi iam finish my server MineCity RP and i really going to need ur help. i try to send u the request but u dont accept new requests.
my Discord:Wesley#5411
My server project: http://www.mcrp.ml/
its bc i dont wanna bother you with any question i have making a issue here in git hub.

**Comment by PikaMug** [comment] 2019-08-29 05:00
Duplicate of #924 

I understand you're in a difficult spot, but I'm unable to assist you further until one of us hears back from the developer of QAV. Please either direct your efforts to contacting them, or be patient.

Please do not open another ticket on this matter or I will be forced to revoke the ability to do so.

**Closed by PikaMug** 2019-08-29 05:00 UTC
