### ISSUE TITLE
People are losing all their progress totally randomly after a server reboot (/restart)

### ISSUE THREAD

**Issue by KoltaiArmy** [PikaMug/Quests#1845] opened 2021-12-12 12:49 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
4.1.3

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I did not found anything in the log related to this problem, maybe this clearlag log helps, but I dont know.
https://pastebin.com/akudA7PR

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
After a server restart, people are random getting all their progress reseted somehow, and I have no Idea why this is happening. Maybe the quest plugin doesn't support the restart command? Or is it because of the new plugin version? I have no Idea what could cause this problem.
Its getting really annoying because its not easy to always add back one by one every single completed quest to the players, there are hundreds of quests on my server.
Every bit of help is appreciated!

**Comment by PikaMug** [comment] 2021-12-12 13:22
Duplicate of #1811

Do not use /restart or /reload

**Closed by PikaMug** 2021-12-12 13:22 UTC
Labels: bug
