### ISSUE TITLE
Could not pass event PlayerItemConsumeEvent to Quests

### ISSUE THREAD

**Issue by Paddiii-Pixeltopia** [PikaMug/Quests#1920] opened 2022-04-09 15:10 UTC
### What is your Quests version / build number (do *not* say "latest")?

Quests v4.3.0-b319

### Describe the problem and how to replicate it.

Could not pass event PlayerItemConsumeEvent to Quests

### Any console errors to share?

```shell
[15:07:09 ERROR]: Could not pass event PlayerItemConsumeEvent to Quests v4.3.0-b319
java.lang.ClassCastException: class me.blackvein.quests.quests.BukkitObjective cannot be cast to class org.bukkit.inventory.ItemStack (me.blackvein.quests.quests.BukkitObjective is in unnamed module of loader 'Quests-4.3.0.jar' @39778ee9; org.bukkit.inventory.ItemStack is in unnamed module of loader java.net.URLClassLoader @5c29bfd)
        at me.blackvein.quests.Quester.finishObjective(Quester.java:3640) ~[Quests-4.3.0.jar:?]
        at me.blackvein.quests.Quester.consumeItem(Quester.java:2935) ~[Quests-4.3.0.jar:?]
        at me.blackvein.quests.listeners.ItemListener.onConsumeItem(ItemListener.java:204) ~[Quests-4.3.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor774.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-283]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:3810) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:1704) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3672) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2282) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3653) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2878) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:269) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:667) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:314) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by PikaMug** [comment] 2022-04-09 15:16
Duplicate of #1919

**Closed by PikaMug** 2022-04-09 15:16 UTC
Labels: bug
