### ISSUE TITLE
Shift click not recognised in Crafting

### ISSUE THREAD

**Issue by Katalijst** [PikaMug/Quests#1154] opened 2020-03-31 18:18 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
Quests version 3.8.8-b75

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Make any quest with a craft as stage completion, and use shift click to get the resulf of the craft, it will not be recognised as crafted.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/UcJhYQ7D

**Comment by PikaMug** [comment] 2020-03-31 18:32
Duplicate of #1067

Some other plugin is affecting the click event. Try removing other non-essential plugins temporarily, then add them back one-by-one until you discover the conflict.

**Closed by PikaMug** 2020-03-31 18:32 UTC
Labels: bug
