### ISSUE TITLE
NPC Kill objective - the NPC's Death is not registering

### ISSUE THREAD

**Issue by HaterKevinKush** [PikaMug/Quests#938] opened 2019-09-12 20:35 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?** No errors. I've had NPC kill quests that worked flawlessly. While creating another i was doing a dry run through and noticed the NPC i was killing, his death would not register triggering the next stage.... i tried a bunch of different things, swapped out npcs, etc. So i went back to one that i knew worked.. Ran through it and low and behold, same thing is happening. Don't know what the issue is worked fine before. 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/9sZA1SMV

**Comment by PikaMug** [comment] 2019-09-26 21:19
Thanks for your report. I wasn't able to replicate the issue. Would you mind trying the latest development build and let me know if the issue perists?

https://ci.codemc.org/job/PikaMug/job/Quests/32/ "Quests-3.8.0.jar"

**Comment by lyimpike** [comment] 2019-09-26 23:03
Same happened to me, 3.8.0 fixes this.

**Comment by PikaMug** [comment] 2019-09-27 06:42
Duplicate of #927

**Closed by PikaMug** 2019-09-27 06:42 UTC
