### ISSUE TITLE
several bugs with the plugin Quests

### ISSUE THREAD

**Issue by victoryne** [PikaMug/Quests#1224] opened 2020-04-19 09:22 UTC
**What is your Quests version / build number (do _not_ say "latest")?**  3.9.2-b94

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
We have a server on paper 629, and have been using Quests for 2 years, but we have some bugs which are not solved for the moment. The quests where you have to kill mobs or break blocks for exemples are very often reset for the players. Therefore we can't have quests where you may break wheat, potatoes or carrotts. Il does not work. With all the resets the players finish by give up quests :( I guess that the reset affect the long quests with lots of mobs to kill or block to break and several stages.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/JhTGHdFe

**Comment by PikaMug** [comment] 2020-04-19 16:55
Duplicate of #1213 

Use https://ci.codemc.io/job/PikaMug/job/Quests/110/

**Closed by PikaMug** 2020-04-19 16:55 UTC
Labels: bug
