### ISSUE TITLE
Does not give money rewards

### ISSUE THREAD

**Issue by xSyke** [PikaMug/Quests#1175] opened 2020-04-05 08:25 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.1.

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
It does not give money reward.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://paste.helpch.at/abidafinum.cpp

**Comment by PikaMug** [comment] 2020-04-05 22:31
Duplicate of #1152 

Use latest dev build https://ci.codemc.org/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-04-05 22:31 UTC
Labels: bug
