### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by lemsol69** [PikaMug/Quests#1436] opened 2020-10-31 09:17 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
v4.0.0-rc.2

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.pl/view/3d7de184 -- this error showed up after I added the above version of quests. What might be the possible error? (Thank you for your time btw, it's appreciated).

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment] 2020-11-01 05:52
Duplicate of #1433

**Comment by PikaMug** [comment] 2020-11-01 06:24
Thanks for the report. Please backup your _Quests/data_ folder and give the following build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/158/

**Closed by PikaMug** 2020-11-01 06:24 UTC
Labels: bug, duplicate
