### ISSUE TITLE
Quests cooldown timer

### ISSUE THREAD

**Issue by DB19222** [PikaMug/Quests#1174] opened 2020-04-05 00:01 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
quests 3.9.0

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When I try to set a cooldown timer on a quest the cooldown sometimes seems to be just gone, sometimes it gets set to 7days instead of the time I set, or just another time. I tried setting the cooldown timer in minecraft and in the files itself. It also says 'need a positive number' when i try to make a cooldown of a month.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/DqN0ddZr

**Comment by louisspaghetti** [comment] 2020-04-05 02:55
I have also been having issues with the cooldown timer, whenever I type in 5 in the in-game quests editor it logs it as 5000 for some reason and I have to manually edit the yml file and reload.

**Comment by PikaMug** [comment] 2020-04-05 03:40
Duplicate of #1161 

Use latest dev build https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-04-05 03:40 UTC
Labels: bug
