### ISSUE TITLE
No display of the task

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#812] opened 2019-05-30 15:22 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.8-b747

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Upon starting quests or when typing /quest after having the quest activated it does not always display what the player is supposed to do.

So far I've only found this being a problem with REDSTONE_BLOCK
and with the quest types; break-blocks and deliver

When a player is supposed to mine 64 Redstone blocks for example, it doesn't tell that to the player, meaning they'd never know unless some player tells them.
Same for Redstone block delivery, it does not tell you that you're supposed to deliver the Redstone blocks.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

This can be done with any quest, possibly multiple items, though I've only found it being a problem with REDSTONE_BLOCK

**Comment by Technodate** [comment] 2019-05-30 19:17
+ This is also the case with GOLD_BLOCK

**Comment by PikaMug** [comment] 2019-05-30 19:23
What is your Minecraft server version?

**Comment by Technodate** [comment] 2019-05-30 19:23
1.8.8

**Comment by Technodate** [comment] 2019-06-02 11:48
Custom 26 Stage 5 does not display the fact that the player has to break blocks.
https://pastebin.com/vUfahsht

Fyi it the amount were to be 64 Redstone blocks for example it wouldn't show up either

**Comment by PikaMug** [comment] 2019-06-03 20:46
Possible duplicate of #787

**Comment by PikaMug** [comment] 2019-06-07 01:36
I created a single-stage quest to attempt to replicate this, but everything works fine:

![redstone](https://user-images.githubusercontent.com/2267126/59076226-f51e6480-88a2-11e9-8a4e-43921509834a.png)

Will try the custom26 quest you've provided next.

**Comment by PikaMug** [comment] 2019-06-07 01:44
Just tested your quest and again, everything works swimmingly:

![gold](https://user-images.githubusercontent.com/2267126/59076424-f2703f00-88a3-11e9-8b52-a21894bb6ae4.png)

Perhaps you need to regenerate your lang files? Also, I'm running the latest dev build so it's possible #802 just fixed the issue. Feel free to comment after the next Spigot release if it does not resolve this issue for you.

**Closed by PikaMug** 2019-06-07 01:44 UTC
Labels: bug, duplicate
