### ISSUE TITLE
Commands rewards are displayed in the chat ... and not working

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#841] opened 2019-07-08 12:53 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

3.7.4
Server's version 1.8.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

When a player ends a quest, all the commands rewards are displayed in his chat, and the commands aren't entered
For example, player 1 finish the quest 1, then he have written in green in his chat:

```
Rewards:
- rg addmembers Zone2 <player>
- class exp <player> 500
- questadmin give <player> Another quest
+ 500 Exp

```
... And all of thoses commands aren't entered, nothing in the console.

Ps: I've switch from Quests 3.6.8 to 3.7.4, in 3.6.8 there are no bugs but i'll had to try the "\n" of the 3.7.4 ... so ... i'm here ^^'

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

Every quests with commands rewards, with or without Op permissions

**Comment by PikaMug** [comment] 2019-07-08 18:12
Command rewards are intentionally shown in chat since Quests 3.7.2, but you can disguise them with an objective-override.

As for the commands not being entered, I'll look into that shortly.

**Comment by tiradorus** [comment] 2019-07-09 00:34
Allright SO!
After many tests, that was just a strange thing with my console and my notifications (Command not shown into the console, but command was entered ... never seen that before, and happening only with quests ... OKAY NO PROBLEM)

Anyway, instead of that the Commands Rewards shown is a bit ... Meh.
And disguise it with an Objective override? Ehhhh, Nah, i can't, Objective overide change the display of the quest, not when you finish the quest and you have written in the chat:
Rewards :
- Bla bla bla
- Bla bla

It's hardly ugly, players don't have to see the commands that a quest give you as a reward, if you want to you just have to add another Command Quests rewards of message to the player.

Or add a way to disable this functionnality xD Into the config for example, cause for the moment, it's the onl reason why i stay on 3.6.8 ... and i've tryed the \n ... It works perfectly, even into MythicMobs Objective ;)
Hardly thanks about that, just i can't use it t'ill the rewards are shown xD

**Comment by PikaMug** [comment] 2019-07-09 02:09
My bad, you are correct about the override not affecting rewards. That's twice I've made that mistake. This is now a duplicate of #738

**Closed by PikaMug** 2019-07-09 02:09 UTC
