### ISSUE TITLE
Quest bug when player disconnect

### ISSUE THREAD

**Issue by Lunatik934** [PikaMug/Quests#1519] opened 2020-12-21 21:41 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
Build 182
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When a player log off, he lost quest's progres. He cant finish or continue
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/nDFbbQDN

**Comment by PikaMug** [comment] 2020-12-22 05:09
Possible duplicate of #1515 

Are you using default YAML storage or MySQL (see [here](https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Storage))?

**Comment by Lunatik934** [comment] 2020-12-22 10:21
I use YAML

**Comment by Lunatik934** [comment] 2020-12-22 10:22
And yea I have the same problem

**Comment by Lunatik934** [comment] 2020-12-23 22:41
Can you fix this problem quickly please ? players need to finish the quest without disconnect

**Comment by PikaMug** [comment] 2020-12-23 22:50
I've been able to replicate the issue, but am still working on a fix. Given the approaching holiday, I'm afraid you'll have to be patient.

**Comment by PikaMug** [comment] 2020-12-25 07:23
Should be resolved in https://ci.codemc.io/job/PikaMug/job/Quests/184/

**Closed by PikaMug** 2020-12-25 07:23 UTC
Labels: bug, duplicate
