### ISSUE TITLE
New Stacktrace error after Updating 

### ISSUE THREAD

**Issue by TheDilPickle** [PikaMug/Quests#1196] opened 2020-04-14 00:37 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.9.3-b99
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**I do not even know anymore what is happening.  All my quests are slowly breaking it feels like after a player takes a quest and relogs back on to do them.  This time it looks like block breaking quests are now broken.  https://pastebin.com/nv3MbWt9

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/rhSmUffq

**Comment by PikaMug** [comment] 2020-04-15 09:05
Duplicate of https://github.com/PikaMug/Quests/issues/1191

**Closed by PikaMug** 2020-04-15 09:05 UTC
Labels: bug
