### ISSUE TITLE
removal of spam message

### ISSUE THREAD

**Issue by elaineandsparky** [PikaMug/Quests#1407] opened 2020-09-16 09:43 UTC
Is there a way to remove these messages when someone takes a quest (using npcs) also i believe it happens when they compelte a quests (but not entirely sure on this). I'm the only one who gets the message as I'm op but as my playerbase grows it gets more and more spammy.

![image](https://user-images.githubusercontent.com/69724087/93320785-628ca500-f809-11ea-8f23-8a83c3007348.png)

**Comment by PikaMug** [comment] 2020-09-16 21:39
Duplicate of #153

`/gamerule sendCommandFeedback false`

**Closed by PikaMug** 2020-09-16 21:39 UTC
Labels: question
