### ISSUE TITLE
Quest rewards being read wrongly

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1156] opened 2020-04-01 15:45 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.0-b84

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I cannot really give you an explanation, we currently have 140+ quests, and since we updated from the last version the cash rewards and quest points rewards switch at random, we just made a fresh test quest and even after setting it back to the correct values dozens of times it kept giving 375,000 quest points and 1 cash... It should have been 1 quest point and 375,000 money. Every time we saved it, it showed properly, however it would still do this after the fact when we reloaded to add the quests.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

[quests (2).zip](https://github.com/PikaMug/Quests/files/4416243/quests.2.zip)

**Comment by PikaMug** [comment] 2020-04-01 17:44
Duplicate of #1152 

Use latest Jenkins build https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-04-01 17:44 UTC
Labels: bug
