### ISSUE TITLE
Quest groups

### ISSUE THREAD

**Issue by CIooIess** [PikaMug/Quests#1421] opened 2020-10-14 03:11 UTC
On a server I admin, I wanted to use this plugin to create a daily/weekly quest system, were an NPC would give a random quest from each category. However, upon detailed inspection of the quest planner, I found out I could only set a specific date & time the quest could be started and a specific reset timer, which means I could only compromise to have specific quests repeat on specific days of the week. 
After testing that, I realized something else: NPC's will always display an uncompleted quest, even if the quest cannot be started yet. This means that the NPC would display every daily & weekly quest option at the same time, until they're progressively completed... _until_ they pile back up from someone _not_ completing them.

So my idea is:
"Quest groups" you can create and add quests to, add to an NPC, and plan with date & reset times- except they don't "complete"; instead they give you either the next quest in the group's list (starting over once it hits the bottom)... or a random one, depending on the option you set. Now, an NPC will show a quest group, like "[DAILY]" or something, and clicking on it will give you a random quest from that group. Upon completion, you won't be able to take another quest from "[DAILY]" until the next day.

I hope you at least consider this idea, and if not, maybe direct me to a plugin or addon that can do this instead.

**Comment by PikaMug** [comment] 2020-10-14 19:38
Thanks for the suggestion. This appears to be a partial duplicate of #796 

Use quest blocks under Edit Requirements to prevent players from taking another quest once completed. If you would like to visually group quests together, just link them all to the same NPC. An example of a daily quest can be found at https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner#daily-quest

**Closed by PikaMug** 2020-10-14 19:38 UTC
Labels: enhancement
