### ISSUE TITLE
Reach Location Bug

### ISSUE THREAD

**Issue by iomatix** [PikaMug/Quests#983] opened 2019-10-24 09:46 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
 3.8.0

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Reach Location mechanic spams chat. When the location is once reached every next block triggers (Completed) Go to Loc. The result is spammed chat.  
`locations-to-reach + reach-location-radii`

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/uFwsmyBV

**Comment by PikaMug** [comment] 2019-10-25 02:56
Duplicate of #922

**Closed by PikaMug** 2019-10-25 02:56 UTC

**Comment by PikaMug** [comment] 2019-11-08 06:14
A build containing the solution to this issue will be available at:
https://ci.codemc.io/job/PikaMug/job/Quests/43/
