### ISSUE TITLE
Bug in NPC Deliveries

### ISSUE THREAD

**Issue by MrNeys** [PikaMug/Quests#2285] opened 2024-08-26 10:02 UTC
### What is your Quests version / build number (do *not* say "latest")?

5.1.0-b495

### Describe the problem and how to replicate it.

When you set a task to bring multiple Items to a NPC and you deliver more of an Item than is requested, it will duplicate said Item in a single stack. That can go up into the millions. You can take the illegal stack and wipe it across the inventory to pull out full stacks of whatever material it is. 

### Any console errors to share?

```shell
*have to enter text here but no console errors to be seen*
```

**Comment by PikaMug** [comment] 2024-08-26 12:34
@MrNeys This sounds like a duplicate of #2280 

Please try the latest development build:
https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed** 2024-08-27 13:31 UTC
Labels: bug
