### ISSUE TITLE
Citizens GUI not showing up

### ISSUE THREAD

**Issue by Masterfixer06** [PikaMug/Quests#1148] opened 2020-03-28 20:19 UTC
Hi there,

I have set up a quest for testing, and everything is going right. Except for one thing: the quest GUI doens't show up. When I click on the Citizens NPC the quest just starts, and no GUI opens up. I find this strange, because I have followed a Quests tutorial [https://www.youtube.com/watch?v=0EZ6yv4MVBM](url) and I have done excactly the same as he did, but with me it doesn't work. Is it maybe because that plugin tutorial is outdated? Or is it because I forgot to enable something in the config file?

Hope you can help me out!

**Comment by PikaMug** [comment] 2020-03-28 20:59
I suspect this is a duplicate of #1146 so please hold until the upcoming release on SpigotMC.

**Comment by PikaMug** [comment] 2020-03-29 08:39
Quests 3.9.0 is now available at https://www.spigotmc.org/resources/quests.3711/

**Closed by PikaMug** 2020-03-29 08:39 UTC
Labels: question

**Comment by Masterfixer06** [comment] 2020-03-29 13:09
Hi there,

I have installed the version 3.9.0, but the GUI still doens't open. Is it because I have forgotten to give permissions or is the bug still not fixed?

**Comment by Stuart-BimboJimbo** [comment] 2020-03-29 13:50
I will answer for Pika as I have had a similar issue. Have you set the GUI Item for the NPC and chosen the correct NPC? Also does Quest/Citizens load correctly? Have you set the `allow-command-quests-with-npcs: true` in the config.yml?

**Comment by Masterfixer06** [comment] 2020-03-29 14:15
Hi there,

Yes, I have set the GUI item and chosen the correct NPC. The quest does start, but the GUI just doens't show up. I had the `allow-command-quests-with-npcs:` on false, but when I set it on true, it still didn't show up.

How can I see if Quest/Citizens load correctly? Do I have to read through the console?

**Comment by Stuart-BimboJimbo** [comment] 2020-03-29 14:17
Yes, please send the startup log via a pastebin link here.

**Comment by Masterfixer06** [comment] 2020-03-29 14:28
Hi there,

I could only copy the last part of my startup log hope it helps: [https://pastebin.com/wMCcXLTS](url)

**Comment by Stuart-BimboJimbo** [comment] 2020-03-29 14:32
Can't see anything wrong there. Do you use 1 NPC per quest or do you have more quests linked to 1 NPC.

**Comment by Masterfixer06** [comment] 2020-03-29 14:34
I currently only have one quest linked to this NPC.

**Comment by Stuart-BimboJimbo** [comment] 2020-03-29 14:35
That might be the reason. Try linking more. I can have one linked to the quest and it first opens the gui. Did you set the "NPC Start" to the NPC?

**Comment by Masterfixer06** [comment] 2020-03-29 14:51
Hi there,

I tried linking two quests to one NPC, but the GUI still does not show up. Even worse, if I click on the NPC, only one quest starts. When I finish this quest and start the other quest, it says 'no more quests available' while I have linked the other quest to that NPC.

I have been thinking, does it maybe still not work because of wrong installation of this plugin? Because this morning I have installed Quests version 3.9.0 and of course I have removed the .jar file of the older Quests version. However, I have kept the Quests folder to keep the current quests. Can this maybe be the error? Because there are a few other things that also don't work smoothly.

I have this plugin installed on a test server to test this plugin, so it won't be a disaster to lose my current plugin data. Should I re-install the plugin?

**Comment by Stuart-BimboJimbo** [comment] 2020-03-29 14:55
Yeah go ahead.

**Comment by Masterfixer06** [comment] 2020-03-29 15:10
Hi there,

Yes, it worked. I have re-installed the plugin and the folder and now the GUI works fine.
![image](https://user-images.githubusercontent.com/61321816/77852661-22e0eb00-71e0-11ea-9465-eb79b5e921ab.png)
Thank you so much for your help, have a nice day!
