### ISSUE TITLE
Quest Decision

### ISSUE THREAD

**Issue by C00kiemax** [PikaMug/Quests#2065] opened 2023-01-25 20:16 UTC
### What does your feature do?

My Idea is that you implement the possibility to choose between two options how you continue with a quest.
For example, when you have to deliver an item to an npc you can decide to deliver or steal it. And however you decide you get different options and ends how the quest continues. 
I have no Idea if its possible to code that, but it would be amazing :o

### How would people use it?

They could you is it quests to make cool storylines and players could talk how they played it and what ends and everything they got.

**Comment by PikaMug** [comment] 2023-01-26 02:54
Duplicate of #1359 (submit a Pull Request or find/sponsor a module).

**Closed by PikaMug** 2023-01-26 02:54 UTC
Labels: enhancement
