### ISSUE TITLE
Automatical set to 0

### ISSUE THREAD

**Issue by Anino75** [PikaMug/Quests#1027] opened 2020-01-03 14:44 UTC
Actually, I work with the 3.8.2 release.
When I am in the quest editor, (after set a name, etc...), I create a stage. I put 3 (NPc), deliver Item, I set my Item correctly (with the name of the Item and the amount of 1). After that, I save the quest, I reload and when I do /quest, it's write "Deliver sign to NPc : 0/0... And with all the Items and all the amount, It's always write 0/0...

**Comment by PikaMug** [comment] 2020-01-03 19:23
Duplicate of #1024

Update to the linked build in that ticket.

**Closed by PikaMug** 2020-01-03 19:23 UTC
