### ISSUE TITLE
Issue when shutdown server

### ISSUE THREAD

**Issue by boristran03** [PikaMug/Quests#1894] opened 2022-03-11 09:29 UTC
### What is your Quests version / build number (do _not_ say "latest")?

4.2.0

### Describe the problem and how to replicate it.

When i stop my server, i got this error

### Any console errors to share?

```shell
[Quests] [STDERR] [Server thread] INFO me.blackvein.quests.libs.hikari.HikariDataSource - quests-hikari - Shutdown initiated...
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: java.sql.SQLException: HikariDataSource HikariDataSource (quests-hikari) has been closed.
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at Quests-4.2.0.jar//me.blackvein.quests.libs.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at Quests-4.2.0.jar//me.blackvein.quests.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:123)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at Quests-4.2.0.jar//me.blackvein.quests.storage.implementation.sql.SqlStorage.getQuesterCurrentQuests(SqlStorage.java:437)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at Quests-4.2.0.jar//me.blackvein.quests.storage.implementation.sql.SqlStorage.saveQuester(SqlStorage.java:256)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at Quests-4.2.0.jar//me.blackvein.quests.storage.Storage.lambda$saveQuester$3(Storage.java:95)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at Quests-4.2.0.jar//me.blackvein.quests.storage.Storage.lambda$makeFuture$1(Storage.java:59)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[16:26:12] [ForkJoinPool.commonPool-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[16:26:12] [Server thread/ERROR]: [Quests] [STDERR] [Server thread] INFO me.blackvein.quests.libs.hikari.HikariDataSource - quests-hikari - Shutdown completed.
```

**Comment by PikaMug** [comment] 2022-03-12 01:47
Duplicate of #1531

**Closed by PikaMug** 2022-03-12 01:47 UTC
Labels: bug
