### ISSUE TITLE
Yes/No message spamming global chat when clicking many times on it.

### ISSUE THREAD

**Issue by MrShiluk33** [PikaMug/Quests#1846] opened 2021-12-13 19:54 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
The Latest version on date so 4.1.3
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I did my quests with Citizens for a Server and since i updated Quests for 1.18, we can now click on Yes/No if we want to accept it. When we click one time there is no problem but if we click again in the chat on Yes or No, it's sending a message for everyone (so Yes or No). Is it possible to fix it so clicking on this message only work once or maybe making an option to disable clicking on chat to accept a quest please cuz i already know some players will make jokes just by spamming right click on the Yes or No. Thanks

Here is the screen when i click only once so it work nice :
[Screenshot_3](https://user-images.githubusercontent.com/96082745/145878800-2c2a344b-2e9f-4d4d-8923-9c8b54dd67bc.png)
But here is what it makes when i click several times on "Yes" (my messages are in French) :
[Screenshot_4](https://user-images.githubusercontent.com/96082745/145878959-a44a3134-ed8e-4556-b029-29b8b58e8e8e.png)

**Comment by PikaMug** [comment] 2021-12-14 04:14
@datatags Any chance you're aware of a fix for this?

**Comment by datatags** [comment] 2021-12-14 08:05
Well, it's directly caused by this code [here](https://github.com/PikaMug/Quests/blob/66d5cfe8eafd269559ca9ea3bfb8a43cae432a2d/api/src/main/java/me/blackvein/quests/Quests.java#L640):
```java
            final TextComponent component = new TextComponent("");
            component.addExtra(ChatColor.YELLOW + getQueryText(context) + "  " + ChatColor.GREEN);
            final TextComponent yes = new TextComponent(getSelectionText(context, 1));
            yes.setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, Lang.get("yesWord")));
            component.addExtra(yes);
            component.addExtra(ChatColor.RESET + " / ");
            final TextComponent no = new TextComponent(getSelectionText(context, 2));
            no.setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, Lang.get("noWord")));
            component.addExtra(no);
```
It could happen with any other clickable prompt though, because the way clickable text is currently handled is sort of a quick-n-dirty fix. Here's a review of the situation, if nothing else to help me think through it again:

Clicking on a clickable prompt just chats the text in the embedded click event, and it's handled entirely by the client, so there's no way of separating chat resulting from clicked text from typed chat.

Another way of doing it, and a better way, would be to add another command, like `/quests choice X` so the server could ignore the command if the player isn't in a conversation. The main barrier to this is using `Player#chat` doesn't register as conversation input, as you previously discovered. The way to get around this is to use `Conversation#acceptInput` manually using the args from the command, but we then have to maintain a reference to any conversations players are in, since there's no method on a player to get the conversation it's in.

A third way that works around those problems (but may create its own) would be to embed an extra string in the message sent when clicking, like instead of the player chatting `yes` or `1`, the player would say `Quests Chat Input#yes` or `Quests Chat Input#1` and whatever follows the # would be the conversation input. The side effects here are requiring a filter layer on prompt input, so whether a player chats `1` (manually) or `Quests Chat Input#1` (using the clickable message), the acceptInput function will get `1` regardless.

I'd be willing to help with these solutions if you like, let me know what you think.

**Comment by MrShiluk33** [comment] 2021-12-14 14:09
Is it possible to make an option to disable clickevent ?

**Comment by datatags** [comment] 2021-12-14 18:42
> Is it possible to make an option to disable clickevent ?

That should be easy enough. The code above would just need to have a config check for a non-clickable menu, and the lines [here](https://github.com/PikaMug/Quests/blob/66d5cfe8eafd269559ca9ea3bfb8a43cae432a2d/api/src/main/java/me/blackvein/quests/convo/QuestsStringPrompt.java#L57) and [here](https://github.com/PikaMug/Quests/blob/66d5cfe8eafd269559ca9ea3bfb8a43cae432a2d/api/src/main/java/me/blackvein/quests/convo/QuestsNumericPrompt.java#L65) would just need to have `|| clickableMenusDisabled` added to the end.

I'm not familiar with how Quests manages the config though

**Comment by PikaMug** [comment] 2021-12-14 23:26
Thanks for the detailed response. I'm thinking the command would be preferable, but I'm also wondering if it's possible to create our own click handler overriding ClickEvent. Not in a position to check this at the moment.

A configuration option is probably a good idea regardless. All config options go through https://github.com/PikaMug/Quests/blob/main/api/src/main/java/me/blackvein/quests/Settings.java

**Comment by datatags** [comment] 2021-12-14 23:37
> Thanks for the detailed response. I'm thinking the command would be preferable, but I'm also wondering if it's possible to create our own click handler overriding ClickEvent. Not in a position to check this at the moment.

I'm pretty sure that's not possible since the client has to understand what to do with the click event.

> A configuration option is probably a good idea regardless. All config options go through https://github.com/PikaMug/Quests/blob/main/api/src/main/java/me/blackvein/quests/Settings.java

I might take a look at doing that this evening then if I have time.

**Comment by MrShiluk33** [comment] 2021-12-14 23:37
Perfect ! If you can let me know when this will be added so i can add it directly into my server to avoid spams in my chat as quickly as possible x) thanks again guys !!

**Comment by PikaMug** [comment] 2021-12-15 09:01
> I'm pretty sure that's not possible since the client has to understand what to do with the click event.
> 
> I might take a look at doing that this evening then if I have time.

You were right, the class is final.

Sure, but don't lose sleep over it.

**Comment by datatags** [comment] 2021-12-15 17:58
> You were right, the class is final.
> 
> Sure, but don't lose sleep over it.
> 
> Edit: I noticed that this triggers the PlayerChatEvent and AsyncPlayerChatEvent. Perhaps a config setting and prescribing an anti-spam plugin might be sufficient.

Good idea, you'd just have to make sure it doesn't interfere with the quests editor where you might click the same number more than once, or interfere with legitimately accepting quests with a couple minutes or so delay.

**Comment by PikaMug** [comment] 2021-12-16 09:33
@MrShiluk33 Your options for resolving this are updating to the [latest development build](https://ci.codemc.io/job/PikaMug/job/Quests/287/) and, after running the plugin once, setting `clickable-text: false` in your _config.yml_ file...

and/or

...use an anti-spam plugin like https://www.spigotmc.org/resources/chatcontrol%E2%84%A2-the-ultimate-chat-plugin-500-000-downloads-1-2-5-1-16-4.271/ (not affiliated)

**Closed** 2021-12-16 09:33 UTC
Labels: bug
