### ISSUE TITLE
Rewards bug

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#1933] opened 2022-04-19 04:26 UTC
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.3.1-b322
server version: Paper 1.18.2

### Describe the problem and how to replicate it.

hello, I don’t know if this could be a bug or not. But many people completing the quest doesn’t receive any rewards automatically. BUT if I force them finish the quest it gives them the reward automatically.

### Any console errors to share?

```shell
Here is the error -> https://paste.gg/p/anonymous/958898ab809947e3a12b5e5a48f60b6d
```

### If applicable, can you provide an example quest from quests.yml?

```shell
Here is the configuration of my Easter quest -> https://paste.gg/p/anonymous/38f7ec61a46f48e784e300d59584773a
```

**Comment by PikaMug** [comment] 2022-04-20 03:25
Duplicate of #1930

**Closed by PikaMug** 2022-04-20 03:25 UTC
Labels: bug
