### ISSUE TITLE
Denizen script from Quest

### ISSUE THREAD

**Issue by stronger108** [PikaMug/Quests#871] opened 2019-07-26 18:16 UTC
**What is your Quests version / build number (do _not_ say "latest")?** 
 Quests version 3.7.6-b${env.BUILD_NUMBER}

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When I assign a task script to a quest the script isn't run at any time of the quest.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://one.denizenscript.com/paste/56090

**Comment by PikaMug** [comment] 2019-07-26 18:32
Duplicate of #845 

Use the latest dev build https://ci.codemc.org/job/PikaMug/job/Quests/

**Comment by stronger108** [comment] 2019-07-27 19:03
Is the latest development build a fix for it or are you just saying stay up to date for a fix? Because the problem still persists after being on the latest development build.

**Comment by stronger108** [comment] 2019-07-27 20:08
I've talked with @SXRWahrheit on the denizen discord and it seems like this is still an issue after fixing #845. I hope I'm not being too annoying with this issue.

When I set a quest to run a denizen script nothing is printed out. Not a single thing. Even after I updated to the dev build of denizen (1.1.0) (Which I wasn't when I first created the issue) and the dev build of quests (3.7.7 #12 in Jenkins). I no longer get the no class defined error but the task scripts still aren't being run when the stage starts or ever. Any ideas?

Here is the entire startup log:
https://one.denizenscript.com/paste/56144

Here is the quests.yml
https://one.denizenscript.com/paste/56142

Here is the script, MYTASK.yml
https://one.denizenscript.com/paste/56143

**Comment by SXRWahrheit** [comment] 2019-07-27 20:09
I directed them to comment on the issue again because there was no Denizen debug output. I'm reopening it so you can investigate.

**Comment by stronger108** [comment] 2019-07-28 21:09
A workaround for those who might have this issue is set a quests action and make that run a command that runs the denizen script. Kind of a big work around but work it does.

**Comment by PikaMug** [comment] 2019-07-30 02:39
@stronger108 Please try https://ci.codemc.org/job/PikaMug/job/Quests/13/

**Comment by stronger108** [comment] 2019-08-01 15:43
Nope :/ Same problem. No output.

**Comment by PikaMug** [comment] 2019-09-06 05:08
This might be resolved with the recent fix for #930 so give this build a try:

https://ci.codemc.org/job/PikaMug/job/Quests/27/

**Warning:** The build linked above is highly experimental. Make sure to back up your Quests folder before attempting to use it.

**Comment by PikaMug** [comment] 2019-09-06 05:09
This might be resolved with the recent fix for #931 so give this build a try:

https://ci.codemc.org/job/PikaMug/job/Quests/27/

**Warning:** The build linked above is highly experimental. Make sure to back up your Quests folder before attempting to use it.

**Comment by stronger108** [comment] 2019-09-06 15:27
It seems to be working now. But its running the scripts at the end of the stage. Is it possible to have an option to run it before instead?

**Comment by PikaMug** [comment] 2019-09-06 19:22
@stronger108 Great! Not to my knowledge, but if you ask on the Discord someone might have a solution. If not, feel free to open a new request ticket.

Thanks for catching the rewards issue. The next build will have that resolved.

**Closed by PikaMug** 2019-09-06 19:22 UTC
Labels: bug
