### ISSUE TITLE
Clickable Confirmations

### ISSUE THREAD

**Issue by trevor1097** [PikaMug/Quests#1728] opened 2021-06-24 16:20 UTC
**What does your feature do?**
Make quest confirmations clickable so players can just click them instead of having to use chat.

**Comment by DeadlykillOfficial** [comment] 2021-06-24 16:30
This sounds like a good idea. But i think based on current state of Quests and how it's coded. I don't think this is possible :(

**Comment by PikaMug** [comment] 2021-06-24 21:59
Duplicate of #618

**Closed by PikaMug** 2021-06-24 21:59 UTC
Labels: enhancement
