### ISSUE TITLE
players lost his progress

### ISSUE THREAD

**Issue by Lunatik934** [PikaMug/Quests#1529] opened 2020-12-31 00:22 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
185
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Hello,
We have a problem with your quest plugin. When a player do a quest but disconnect he lost his progress. Our server run under BungeeCord and when a player travel between servers he don't lose his progress, only when he totally disconnect. That's problematic because some quest can take a lot of time to be completed. I hope you're understanding the problem.
Best regards.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/Xx49iNaG

**Comment by PikaMug** [comment] 2020-12-31 01:10
This is a known limitation of the MySQL implementation and will be addressed in a future build.

**Comment by Lunatik934** [comment] 2020-12-31 10:26
I don’t use MySQL I have a file db

**Comment by DeadlykillOfficial** [comment] 2020-12-31 10:34
File DB is technically a SQL database that's part of MySQL family. I've recently tested YML storage about this issues on b185 and it was working without any issues.

**Comment by Lunatik934** [comment] 2020-12-31 10:47
Not work for me please try my quests config

Le jeu. 31 déc. 2020 à 11:35, Deadlykill <notifications@github.com> a
écrit :

**Comment by DeadlykillOfficial** [comment] 2020-12-31 17:41
I could have tried it. But since your Quests provided aren't valid. I can't do that for you.

**Comment by Lunatik934** [comment] 2021-01-01 05:48
Just remove the requierements

**Comment by Lunatik934** [comment] 2021-01-04 03:08
When I start the quest: https://puu.sh/H3AjO/f106a5417a.png

After disconnect: https://puu.sh/H3AkG/1d77b6a1a1.png

**Comment by DeadlykillOfficial** [comment] 2021-01-04 09:40
before i disconnect:
![image](https://user-images.githubusercontent.com/12415714/103521501-28f3ae80-4e79-11eb-8c0d-1a1721857f70.png)

After i have disconnected:
![image](https://user-images.githubusercontent.com/12415714/103521536-37da6100-4e79-11eb-8e64-4b50b0d1b675.png)

**Comment by DeadlykillOfficial** [comment] 2021-01-04 09:42
test with Zombies:
Before DC:
![image](https://user-images.githubusercontent.com/12415714/103521643-66f0d280-4e79-11eb-95c2-4c4b50dfef76.png)

After DC:
![image](https://user-images.githubusercontent.com/12415714/103521678-753eee80-4e79-11eb-9ff4-16c554f2f9ca.png)

This "problem" is unable to be replicated. i'm using b189 for both tests.

**Comment by Lunatik934** [comment] 2021-01-04 10:21
Not fixed on b189

**Comment by DeadlykillOfficial** [comment] 2021-01-04 10:24
I just confirmed it's fixed dude? I've literally just tested it and confirmed it is working properly with YML file storage.
You must investigate why is your server no willing to save it. This issue cannot be replicated therefor can't be fixed (cause it's working properly)

**Comment by DeadlykillOfficial** [comment] 2021-01-04 11:13
@PikaMug After further investigating. It turns out that having `.` in Quest Name does mess with the YML pathing in saving process.
Where following quest: https://hastebin.com/usuwaforiv.yaml
Does provide this outcome in data files: https://hastebin.com/urufagifev.yaml
Where the name containing YML path splitter `.` does mess with saving preventing from loading progress later on.

**Comment by PikaMug** [comment] 2021-01-04 20:49
Thanks @DeadlykillOfficial for looking into this further. While the symptoms are similar to a caveat we're having with MySQL, this is indeed being caused by the period in your quest name. In the /quests editor, you will get _"Name may not contain periods or commas!"_ when creating the quest name, so it seems it must have been added manually. While a recent commit (https://github.com/PikaMug/Quests/commit/325522d9dbe5917aa7113f08ecc9936b35b68905) took a step towards allowing such characters, this is not supported yet. I'm afraid you'll need to rename the quest and edit or reset the data of any affected players.

**Closed by PikaMug** 2021-01-04 20:49 UTC
Labels: bug
