### ISSUE TITLE
Quest's not working. Cannot be accepted.

### ISSUE THREAD

**Issue by StormyBlueyss** [PikaMug/Quests#883] opened 2019-07-30 20:00 UTC
Hello I updated and i am having a problem. Im sorry for being a inconvenionce. None of my players can accept a quest other then myself but my guess that is due to me being OP. They can get the for example run ./quests take Iron Miner -> into it the chat saying "Accept Quest" Yes Or No. When a player that is not OP says Yes in chat nothing happens. No Animation No Accualy accepting the quest just nothing. Any Ideas?

Console Stuff:

https://pastebin.com/A2u3XLJJ

**Comment by PikaMug** [comment] 2019-07-30 20:12
Duplicate of #877 

Use https://ci.codemc.org/job/PikaMug/job/Quests/14/

If that doesn't work, you can also disable the Yes/No prompt in config.yml by changing to `ask-confirmation: true` to `ask-confirmation: false`.

**Closed by PikaMug** 2019-07-30 20:12 UTC
Labels: bug, duplicate
