### ISSUE TITLE
Objective Progress Duplication Bug

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#1952] opened 2022-05-06 23:36 UTC
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.4.0-b328
Paper version: 1.18.2

### Describe the problem and how to replicate it.

It seems like when players use a **silktouch** pickaxe to mine all types of ores like emerald, diamond, etc as their quest, it duplicates. For example players needs to mine 0/1024 emerald ores and uses a silktouch pickaxe to mine 5 ores the quest system tells them they mined 7 or 9 sometime instead of 5 ores. **This issue occurs if you place the ore's down yourself and then mine them which causes the duplication.**

### Any console errors to share?

```shell
No console error
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Here's the quests.yml -> https://www.toptal.com/developers/hastebin/guzabipuna.yaml
```

**Comment by AlmightyPest** [comment] 2022-05-06 23:55
A bit more detail^^

So when a player breaks an ore with a pickaxe that has silk touch and placed it back down it'll count it toward the quest. I.e. I have a quest where I need to break 10 emerald ores. I place down 3 emerald ores, break them with silk touch, place them back down, break them, I get 6 emerald ores broken for the quest. That's 6/10 emerald ores broken.

Players shouldn't be able to place down the ores for the quest to count them, I'm assuming. (This happens to all ores)

**Comment by PikaMug** [comment] 2022-05-07 03:18
Does this still occur on https://ci.codemc.io/job/PikaMug/job/Quests/330/ ?

**Comment by AccioAce** [comment] 2022-05-08 05:12
> Does this still occur on https://ci.codemc.io/job/PikaMug/job/Quests/330/ ?

Hello, nope it doesn't seem to work since another bug occur. I notice that when I tried to break the ore's with silk touch and non silk touch pickaxe none of the progress is being process through.

**Comment by PikaMug** [comment] 2022-05-08 15:23
The quest link you provided is empty or expired. I tested this with the following quest on build 330 and it worked fine; blocks broken incremented by 1 every time using a new Diamond Pickaxe with Silk Touch.

```yaml
  custom36:
    name: silkTouch
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - IRON_ORE
          break-block-amounts:
          - 20
          break-block-durability:
          - 0
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

**Comment by AlmightyPest** [comment] 2022-05-08 15:53
https://user-images.githubusercontent.com/105087378/167304240-12fbad39-474c-4f66-a0a3-d1c8d87bd5ed.mov

In that video^^ is what I mean by placing the block down and the plugin counting it. I don't think it's supposed to be like that (where players can place down the ore/block/objective and it counting it; normally it's been where you have to find it in the wild (world generated)).

You can see I had 12 ores mined, placed down 3, and it went up to 15.

**Comment by PikaMug** [comment] 2022-05-08 16:16
I see, so this is a duplicate of #1951 which was fixed in #1953 and I just confirmed that build 330 fixes that. Can you check what version you have installed with the _/quests info_ command?

**Comment by AccioAce** [comment] 2022-05-09 06:58
> I see, so this is a duplicate of #1951 which was fixed in #1953 and I just confirmed that build 330 fixes that. Can you check what version you have installed with the _/quests info_ command?

Hello, It seems like mining the ore's with and without silk touch pickaxe, there isn't any progress as well. I tested it out with #330 build.

**Comment by AccioAce** [comment] 2022-05-09 07:19
@PikaMug Hello,
so I've tested with build #331 quest version. So what I found out that if I place 1-3 emerald ores at once down then mine it afterward it seems like the progress doesn't count toward it. But if I place like 5-10 ores at the same time before mining it the progress counts toward it. I don't know if that make any sense?

**Comment by PikaMug** [comment] 2022-05-09 07:23
The number of ore placed down shouldn't make a difference. Maybe you have a region/protection plugin interfering?

**Comment by AccioAce** [comment] 2022-05-09 07:24
> The number of ore placed down shouldn't make a difference. Maybe you have a region/protection plugin interfering?

It seems to be making the differences. Nope I have no region/protection plugin within the area when I tested it out.

**Comment by PikaMug** [comment] 2022-05-09 08:05
I still can't access your example quest. Feel free to share it again.

**Comment by AccioAce** [comment] 2022-05-09 08:07
> I still can't access your example quest. Feel free to share it again.

Hello it must had expired but here it is -> https://www.toptal.com/developers/hastebin/wipuwarale.yaml

**Comment by AccioAce** [comment] 2022-05-13 06:13
@PikaMug Hello any updates?

**Comment by PikaMug** [comment] 2022-05-13 10:54
Just tried your quest, and placing Emerald Ore then mining it with a Diamond Pickaxe with Silk Touch yielded expected results. Placing more down and then mining also worked fine. Granted I'm testing with the Quests 4.4.1 release, but using Paper 1.18.2 as well so the only explanation I can think of is a plugin conflict (even if a region isn't specified in the testing area). I recommended temporarily removing all non-essential plugins except Quests to check if that alleviates the issue. Closed pending more information.

**Closed by PikaMug** 2022-05-13 10:54 UTC
Labels: bug, duplicate, help wanted
