### ISSUE TITLE
Quests not able to be accepted through commands/not recognized as existing.

### ISSUE THREAD

**Issue by Sinnerrrr** [PikaMug/Quests#1334] opened 2020-06-24 08:21 UTC
**Where else have you looked for answers to this question?**

I've looked through all of the pages of documentation provided in terms of config and command usage/setup, as well as various FAQs but haven't seen anyone else with this issue.

--

I am using a plugin for World Guard that allows my regions to execute commands on entry (in this case, I wanted players to automatically receive a quest when they entered an area) which gives me the prompt telling me that the quest I created couldn't be accepted via commands when I enter it, however when I attempt to accept the quest manually I'm told that no such quest exists. I can edit the quest, the World Guard regions seem to recognize it as a valid quest, however whenever I attempt to accept a quest via the /quest take or the /questadmin give command, I am told that no such named quests exist. I have reloaded the quests multiple times and have saved and created new, blank quests as controls and I am still unable to accept them via command or region. Reloading the server had no effect.

Is there something I'm missing in my setup? I have not edited any requirements save for the player having to be within a certain region and block radius in order to accept the quest, and I enabled both "allow-command-questing" and "allow-command-quests-with-npcs" in the config. The quests I have created appear in the quests.yml file, and there's nothing that I can tell would be preventing me from accepting quests as an operator or as a normal player. No errors show in the server console either.

I am also using Citizens 2 in conjunction with this plugin, if that should be relevant.

I hope this was coherent, as I'm very tired. 

Thank you!

**Comment by PikaMug** [comment] 2020-06-24 08:45
Possible duplicate of #1264 

Kindly open a new ticket as a Bug Report, following the template with Quests version and example quest.

**Closed by PikaMug** 2020-06-24 08:45 UTC
Labels: question
