### ISSUE TITLE
ERROR Could not pass event NPCRightClickEvent to Quests v5.0.2-b469

### ISSUE THREAD

**Issue by gamelamp** [PikaMug/Quests#2216] opened 2024-05-29 16:38 UTC
### What is your Quests version / build number (do *not* say "latest")?

Quests v5.0.2-b469

### Describe the problem and how to replicate it.

When right-clicking a citizen NPC I get thrown the error after trying to complete a quest (hand in 64 oak logs for this specific quest)
The console also throws me this WARN:
WARN]: [Quests] LocaleLib not present! Is this a debug environment?
But I am quite sure that LocaleLib is installed

I am using:
Citizen: Citizens-2.0.34-b3417.jar
Minecraft: 1.20.6
Paper for the server
LocaleLIB: LocaleLib-3.9.jar

### Any console errors to share?

```shell
[16:27:28 ERROR]: Could not pass event NPCRightClickEvent to Quests v5.0.2-b469
java.lang.NullPointerException: Cannot invoke "me.pikamug.quests.libs.localelib.LocaleManager.sendMessage(org.bukkit.entity.Player, String, org.bukkit.Material, short, java.util.Map)" because the return value of "me.pikamug.quests.BukkitQuestsPlugin.getLocaleManager()" is null
        at Quests-5.0.2.jar/me.pikamug.quests.player.BukkitQuester.finishObjective(BukkitQuester.java:3495) ~[Quests-5.0.2.jar:?]
        at Quests-5.0.2.jar/me.pikamug.quests.player.BukkitQuester.deliverToNPC(BukkitQuester.java:2683) ~[Quests-5.0.2.jar:?]
        at Quests-5.0.2.jar/me.pikamug.quests.listeners.BukkitCitizensListener.onNPCRightClick(BukkitCitizensListener.java:91) ~[Quests-5.0.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor358.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-82-0ad09de]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at Citizens-2.0.34-b3417.jar/net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:592) ~[Citizens-2.0.34-b3417.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor259.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-82-0ad09de]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.performInteraction(ServerGamePacketListenerImpl.java:2773) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onInteraction(ServerGamePacketListenerImpl.java:2821) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:138) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2762) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1514) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1414) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1380) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by PikaMug** [comment] 2024-05-29 18:08
Likely duplicate of #2215 please try the latest dev build

**Comment by PikaMug** [comment] 2024-05-29 18:17
The build linked in that issue. Also, you don't need the LocaleLib jar; it's already included in Quests.

**Comment by gamelamp** [comment] 2024-05-29 18:20
> The build linked in that issue. Also, you don't need the LocaleLib jar; it's already included in Quests.


Thank you, will test it out :)

**Comment by gamelamp** [comment] 2024-05-29 18:25
> The build linked in that issue. Also, you don't need the LocaleLib jar; it's already included in Quests.

Hmm, nope. I seem to get another error now, when accepting the quest:
[](https://paste.gg/p/anonymous/a258f892e2e440e98ed21207467618ea)
I'm using the build version from the other issue

**Comment by PikaMug** [comment] 2024-05-29 18:46
@gamelamp Thanks for that. Give https://ci.codemc.io/job/PikaMug/job/Quests/471/ a try and, if you find any more problems, please open a new issue.

**Closed by PikaMug** 2024-05-29 18:46 UTC
Labels: bug
