### ISSUE TITLE
Actions not starting past Stage 1 or Initial Action phase of quest

### ISSUE THREAD

**Issue by dkhawser** [PikaMug/Quests#855] opened 2019-07-19 16:19 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.7.1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Actions seem to only initialize at the START of a quest either in the "Initial Action" phase of the quest, or at the beginning of Stage 1
But I'm trying to make it so that Stage 1 is where a player would have to first Reach a location. then after they've reached that location, Stage 2 starts and THAT is when the Action will happen, which in this case, is that mobs would then spawn around that location.
However when Stage 2 Starts, the Action does not initialize.

The Action DOES work if i put it in Stage 1, but not if I put it in Stage 2 or beyond.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment] 2019-07-19 19:01
Duplicate of #838

**Closed by PikaMug** 2019-07-19 19:01 UTC
