### ISSUE TITLE
Quest Journal Error

### ISSUE THREAD

**Issue by Surplexed** [PikaMug/Quests#1248] opened 2020-04-23 18:31 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.93-b107

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Anytime I try to use the journal you get when you do the /quest journal command, I get kicked to the hub with this error https://hastebin.com/witajaxije.css. The servers codebase is 1.8.9, but we allow up as far as 1.12.2. I tried on both versions and it still kicks me to the hub. I was told that its something to do with a protocal error in my server software but I would like to know can I use the latest builds of quest on 1.8.9. If so how do I stop this from happening. If not than what is the latest version I can use on 1.8.9. Thank you

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
N/A

**Comment by PikaMug** [comment] 2020-04-24 05:07
Possible duplicate of #1233

Thanks for the report. Your Hastebin link does not appear to be valid.

Please try the latest development build and report back with any errors https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-04-24 05:07 UTC
Labels: bug

**Comment by Surplexed** [comment] 2020-04-24 18:31
Still the same issue, here is the error https://pastebin.com/U8H4ZGwy

**Comment by PikaMug** [comment] 2020-04-24 22:10
Thanks. I think the Hastebin website might not have been working earlier - I can see it now. Anyway, the error you've shared isn't directly from Quests. A quick Internet search tells me this is either outdated server software (there might be a newer build for 1.8.9 available) or you're using a plugin that modifies packets (ProtocolLib, LibsDisguises, ViaVersion, etc.) and it's doing something wrong.

All I can recommend is that you [repeat the same search](https://lmgtfy.com/?q=io.netty.handler.codec.DecoderException%3A+java.lang.RuntimeException%3A+An+internal+error+occured.) and try a few of those fixes within, or ask for help pinpointing the issue on the SpigotMC forums.

**Comment by Surplexed** [comment] 2020-04-24 22:38
We are using ProtocalLib and ViaVersion, the most up to date versions and its a custom Jar

**Comment by Surplexed** [comment] 2020-04-27 00:33
Any help on this because I wanna use the newer features instead of using a older version

**Comment by PikaMug** [comment] 2020-04-27 01:38
This is not something I can assist with. Although opening a book from Quests is reportedly the catalyst, the issue lies with either your custom jar or another plugin. Unfortunately, the error doesn't give a clear indication of which. My recommendation is to reach out to the creator of your server software first, then if they're unable to help, try the ProtocolLib/ViaVersion teams.

Note you could also just disable the Quests Journal by revoking the `quests.journal` permission, or consider upgrading to QuestsGUI and use the alternative GUI.
