### ISSUE TITLE
Daily quests

### ISSUE THREAD

**Issue by Starkitobonito** [PikaMug/Quests#1371] opened 2020-07-31 00:35 UTC
**What does your feature do?**
Pls, add in the planning like restart time, with this the mission will restart at certain hour, like all the dailys are going to restart at 00:00 am, and at that hour, the players can make de quest again, and the same after that hour.
**How would people use it?**
That is for avoid the cooldown of the planner, Players cannot always enter at the same times every day. It would be better if the mission is available per day, and you do not have to wait necessarily 24 hours or less for make the quest again.

**Comment by PikaMug** [comment] 2020-07-31 03:31
Duplicate of #1244

**Closed by PikaMug** 2020-07-31 03:31 UTC
Labels: enhancement
