### ISSUE TITLE
IndexOutOfBoundsException on plugin reload (and other occasions)

### ISSUE THREAD

**Issue by nightscout01** [PikaMug/Quests#1273] opened 2020-04-30 06:47 UTC
What is your Quests version / build number (do not say "latest")?: 3.9.3-b107
Server Version: PaperMC git-Paper-112 (MC version 1.15.2)

The problem we are facing is this message: "An internal error occurred while attempting to perform this command" or "An unknown error occured" and the accompanying Java stacktrace that gets printed to the console whenever we attempt to reload the plugin. I have attached the console stacktrace here:
https://pastebin.com/0S7VCzHt

We've encountered this error intermittently throughout our time with the Quests plugin.
The heart of the issue seems to stem from a player interacting with a quest that's being edited by joining it, or possibly interacting with their journal while the quest is being edited (we're not quite sure about that one). That player's profile appears to become "corrupted" somehow. If a player with a "corrupted" profile is on the server when the /qa reload command is executed, the command fails with an error and dumps the attached stacktrace to the server console. Other quest commands seem to become unstable when a player with a "corrupted" profile is online as well, but do not have easily repeatable issues like the errors on reload. 

When a player with a "corrupted" profile joins the server, we also get the following errors in console:
https://pastebin.com/fmu8TMb6

Deleting their profile from the data folder appears to fix the issue, but the fact that their presence on the server causes issues to other players is quite strange indeed.

If you wish for a sample quest from the yml I have attached one here:
https://pastebin.com/qZSVvxhx

Thanks for any help you may be able to give!

**Comment by PikaMug** [comment] 2020-05-01 04:16
Duplicate of #1233

Use latest development build (may break QuestsGUI til next release):
https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-05-01 04:16 UTC
Labels: bug
