### ISSUE TITLE
Toggle for "Condition not yet met for this stage of <quest>." message

### ISSUE THREAD

**Issue by MarxminSD** [PikaMug/Quests#1958] opened 2022-05-09 20:19 UTC
### What does your feature do?

Currently, if a player doesn't meet the requirements for a stage/objective, they'll see a "Condition not yet met for this stage of [quest]." message, as seen below.

![image](https://user-images.githubusercontent.com/96161173/167489781-ae9235d8-b469-401e-8187-400819791270.png)

In some cases, quests may have specific conditions a player needs to meet, but also be fairly lengthy resulting in players potentially taking breaks or working on other miscellaneous activities white the quest is active. 

For example, the town Blacksmith asks a player to "test out" a set of armor by killing X number of mobs with that armor set equipped. If the number is rather high, the player may take a break to go mining, build, or farm. The player will consistently see the "Condition not yet met for this stage of [quest]." message if they aren't wearing that set of armor. 

I think it would be really cool if we could perhaps toggle that message either for all quests, or on a condition by condition basis (I'm not sure how it's handled in the plugin :P).

### How would people use it?

Admins and quest-makers could create longer quests with more specific conditions without players constantly seeing the "Condition not yet met for this stage of [quest]." message - which can get a little cluttered/annoying at times :P

**Comment by PikaMug** [comment] 2022-05-10 09:16
Duplicate of #1861 

You can extend the interval between messages by setting `condition-interval` in config.yml between 3 and 180 seconds.

**Closed by PikaMug** 2022-05-10 09:16 UTC
Labels: enhancement

**Comment by MarxminSD** [comment] 2022-05-10 17:30
Thanks!
