### ISSUE TITLE
Actions and Events both exist in the events.yml file, possible typo?

### ISSUE THREAD

**Issue by boopdev** [PikaMug/Quests#817] opened 2019-06-02 03:54 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.0

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Making events is broken, it appears that while the 'actions' section does exist in the actions.yml, when attempting to create any new actions, they get put under a completely new section, titled "events" which is what the old name for actions were. There's no errors in the terminal, this is probably just a typo anyways

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
quests.yml isn't the issue, here's my actions.yml [link redacted]

**Comment by boopdev** [comment] 2019-06-02 03:55
sorry, all my edits didn't save, it'll be edited shortly if it hasn't already

**Comment by PikaMug** [comment] 2019-06-02 06:58
Although I recognize this is a valid issue, the language in your linked Pastebin will not be tolerated here. I've taken note of the problem, but must lock the conversation and remove the link to your post. This ticket will be updated once the issue is resolved.

**Comment by PikaMug** [comment] 2019-06-03 00:52
Fixed in #818

**Closed by PikaMug** 2019-06-03 00:52 UTC
Labels: bug

**Comment by PikaMug** [comment] 2019-06-03 00:55
Fixed in https://github.com/PikaMug/Quests/commit/e919554e59807fde46509f09711ad7a067e17a9d
