### ISSUE TITLE
Failed loading lang files

### ISSUE THREAD

**Issue by VirtualPixel** [PikaMug/Quests#874] opened 2019-07-27 07:12 UTC
**What is your Quests version / build number (do _not_ say "latest")?** 3.7.7-b12

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?** https://pastebin.com/qZYMtm1b

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

I changed permissions of the /plugins folder to allow everything for group "Everyone", deleted the Quests folder so that it would generate a new one and it still came back with the same issue. 
![image](https://user-images.githubusercontent.com/32817116/61991316-539ece00-b01c-11e9-9509-eaa239cddef7.png)

![image](https://user-images.githubusercontent.com/32817116/61991324-631e1700-b01c-11e9-8792-07f4c786997b.png)

**Comment by PikaMug** [comment] 2019-07-27 17:50
Duplicate of #873

**Closed by PikaMug** 2019-07-27 17:50 UTC
