### ISSUE TITLE
No translation of item names

### ISSUE THREAD

**Issue by chelminski** [PikaMug/Quests#2104] opened 2023-05-12 16:52 UTC
### Where else have you looked for answers to this question?

Hi ;)
_Reply to a closed thread: https://github.com/PikaMug/Quests/issues/2103_

### To reproduce the problem:

- I deleted all Quests plugin files, restarted the server to regenerate them
- I created a new test quest
- I didn't change config
- The language of the game is set to Polish by default

The quest consisted of delivering 64 pieces of wood to the NPC

1) The first error I see is that in the case of the default config, part of the text is in Polish and part in English. When I automatically try to confirm a quest in English, a message pops up asking me to choose "Tak" or "Nie".
[https://drive.google.com/file/d/1l7BnFrYbtWQwE3vPAoIWg1tN5BVxgAZX/view?usp=sharing](url) - video

2) The second thing is items are not displayed in their native language. I changed the config so that instead of the default "en-US" it was "pl-PL". Also after changing the language force for the player, some subtitles started to show up in English by default.
(f.e. "Challenge Objectives!")
[https://drive.google.com/file/d/1KH6pcpNaY-xdiQq8z3Whco2ZtTvVQNK-/view?usp=sharing](url) - video

### Share your question with as much detail as possible.

[CONFIG]

accept-timeout: 20
allow-command-questing: true
allow-command-quests-with-npcs: false
allow-pranks: true
clickable-prompts: true
condition-interval: 10
confirm-abandon: true
confirm-accept: true
console-logging: 2
disable-command-feedback: false
generate-files-on-join: true
give-journal-item: false
ignore-locked-quests: false
kill-delay: 600
language: pl-PL
language-override-client: true
max-quests: 0
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: heart
show-completed-objectives: true
show-requirements: true
show-titles: true
storage-data:
  address: localhost:3306
  database: minecraft
  username: root
  password: ''
  table_prefix: quests_
  pool-settings:
    max-pool-size: 10
    min-idle: 10
    max-lifetime: 1800000
    keepalive-time: 0
    connection-timeout: 5000
    properties:
      useUnicode: true
      characterEncoding: utf8
storage-method:
  player-data: yaml
strict-player-movement: 0
top-limit: 150
trial-save: false
translate-names: true
translate-subcommands: false
update-check: true

### 
No matter what I change in config, it still doesn't work. What may be the problem?

**Comment by PikaMug** [comment] 2023-05-12 21:52
Duplicate of #2103 (also wrong template)

**Closed by PikaMug** 2023-05-12 21:52 UTC
Labels: question
