### ISSUE TITLE
Colon's in item lore.

### ISSUE THREAD

**Issue by CachedCode** [PikaMug/Quests#808] opened 2019-05-28 11:29 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.8
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When creating a custom item reward, lores with colons in them do not work and produce a console error. I understand that you can change the seperator to a semi-colon using (charSemi) in lang. However, even when my charSemi: ";" , the colon's produce an error, if I change the separators in quests.yml to a semi colon as per charSemi, it produces an error, how can I fix this to use colons in my lore? Thanks.

Console Error with charSemi as a semi colon and separators as a colon: https://pastebin.com/BLiTBY92

Console Error with charSemi as a semi colon and separators as a semi colon:
https://pastebin.com/8VTATMuy

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Example Provided in First Pastebin link.

**Comment by PikaMug** [comment] 2019-05-28 13:27
Duplicate of #275

YAML (the config format for most Bukkit plugins) uses colons as data separators, so using them in lore simply isn't going to work. I'll look into rejecting items that contain a colon in the future.

**Comment by CachedCode** [comment] 2019-05-29 08:10
> Duplicate of #275
> 
> YAML (the config format for most Bukkit plugins) uses colons as data separators, so using them in lore simply isn't going to work. I'll look into rejecting items that contain a colon in the future.

Ah no worries, from my understanding I read that you had solved this issue with the charSemi, thanks for the reply, just a miscommunication.

**Comment by PikaMug** [comment] 2019-05-29 08:18
Actually, you might be right. Could be something changed recently that broke that functionality. Hope to look into it soon.

**Comment by CachedCode** [comment] 2019-05-29 08:25
> Actually, you might be right. Could be something changed recently that broke that functionality. Hope to look into it soon.

Appreciate it :D changing your .split() to include charSemi will probably fix it (if that's the way you have it setup)

**Comment by PikaMug** [comment] 2019-06-29 22:31
So it looks like charSemi is/was only being used for in-game prompts where Quests asks for a list of units separated by a semicolon. It doesn't have any effect on the config file.

That said, I'm working on a version of Quests which supports colons through a Bukkit implementation. If you'd like to test it, _back up your files_ and then use this jar:
https://www.dropbox.com/s/zliyeo1a3tbd0kb/Quests-3.8.0-beta1.jar?dl=0

**Comment by PikaMug** [comment] 2019-09-06 05:03
`Resolved with recent dev builds which use an improved method for storing Itemstacks. After updating, you'll have to open the quest in the editor, then save it and run _/questadmin reload_.

https://ci.codemc.org/job/PikaMug/job/Quests/

**Warning:** The builds linked above are experimental. Make sure to back up your Quests folder before attempting to use it.`

**Closed by PikaMug** 2019-09-06 05:03 UTC
Labels: duplicate, enhancement
