### ISSUE TITLE
Can Not Set MCMMO requirements

### ISSUE THREAD

**Issue by PlayAmnesiaNightCom** [PikaMug/Quests#856] opened 2019-07-19 18:13 UTC
I'm in the middle of trying to setup a quest and I'm at the MCMMO requirements and this comes up no matter what I do. 
Doing /quest put me out of the menu and back to the setup of that quest, so nothing lost. I do have the newer MCMMO made by the original devs. Not sure if that matters

**What is your Quests version / build number (do _not_ say "latest")?**
v3.7.3

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/MYmteTXC

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Still in the middle of creating the quest. It's my first quest ever so I don't have any files for it.

**Comment by PikaMug** [comment] 2019-07-19 19:00
Duplicate of #853 

mcMMO Overhaul not yet supported. See #794

**Closed by PikaMug** 2019-07-19 19:00 UTC
