### ISSUE TITLE
Entity death events, Java error 1.8.8

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#785] opened 2019-05-04 23:06 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.7-b735
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Java errors, Plugin can't understand the entity death event:

```
01:01:17: Could not pass event EntityDeathEvent to Quests v3.6.7-b735
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:371) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:877) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.EntitySkeleton.die(EntitySkeleton.java:142) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
at com.gmail.berndivader.mythicmobsquests.MythicMobsKillObjective.onMythicMobDeathEvent(MythicMobsKillObjective.java:67) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
... 23 more
```

Server's version: 1.8.8

**Comment by PikaMug** [comment] 2019-05-05 01:58
Appears to be duplicate of https://github.com/BerndiVader/MythicMobsQuestsModule/issues/35

Seems I broke something with Quests 3.6.6 which only affects the current release of the MythicMobs module (no others as far as I can tell). I'm afraid you'll have to wait until the above issue is resolved. In the meantime I advise updating to Quests dev build http://ci.ac3-servers.eu/job/Quests/735/

**Comment by tiradorus** [comment] 2019-05-05 13:03
No problem, i'm using the 3.6.4 for the moment ^^' It works well, just i've updated the plugin, and throws me soe errors, so i'll post it here, and back-up to 3.6.4 :D

**Closed** 2019-05-07 06:56 UTC
Labels: bug

**Comment by PikaMug** [comment] 2019-05-07 06:58
Will be fixed in http://ci.ac3-servers.eu/job/Quests/736/ once it's available
