### ISSUE TITLE
Kicked for Illegal Characters in Chat When Clicking Quest Names in Editor

### ISSUE THREAD

**Issue by dsevvv** [PikaMug/Quests#1905] opened 2022-03-22 19:26 UTC
### What is your Quests version / build number (do _not_ say "latest")?

Quests 4.2.2

paper 1.18.1-216

### Describe the problem and how to replicate it.

In the /quests editor, when I am given the list of quests to edit, I will attempt to click a quest name to begin editing it.

I am unable, I am immediately kicked for "Illegal Characters in Chat".

Yes, my account is a server operator.

I will answer some of the questions I was asked in the discord support here to save some time in case you want to ask the same questions.

No I have not edited any of the data files manually.

I do use a chat manager, Luck Perms Chat, I also have multiple other plugins that support clicking things in chat which function with no issue."

Also, once I actually get into the quest editor by typing the name into chat, I AM able to click the individual options like 1 - Set name, 2 - Set ask message etc.. which is very strange.

### Any console errors to share?

```shell
None, just get kicked for "Illegal Characters in Chat"
```

### If applicable, can you provide an example quest from quests.yml?

```shell
custom2:
    name: '&4&lDragon Slayer | Part 1'
    ask-message: Do you believe you can slay the dragon?
    finish-message: Impressive... take this.
    npc-giver-id: 21
    requirements:
      quest-points: 20
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Ender Dragon
          mob-amounts:
          - 1
        '2':
          npc-ids-to-talk-to:
          - 21
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2865
        type: DRAGON_EGG
        amount: 4
      quest-points: 5
      exp: 1000
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

**Comment by dsevvv** [comment] 2022-03-22 19:29
Side note, love this plugin 10/10 thank you for your work.

**Comment by PikaMug** [comment] 2022-03-22 22:35
Duplicate of #1902 but I'll keep this open pending investigation. Does this still happen if you remove non-essential plugins including LuckPermsChat?

**Closed** 2022-03-23 07:48 UTC
Labels: bug
