### ISSUE TITLE
Stacktrace

### ISSUE THREAD

**Issue by supertakeru** [PikaMug/Quests#1193] opened 2020-04-13 02:05 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.9.2
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Console error only
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/nfFfNRdD

**Comment by PikaMug** [comment] 2020-04-13 02:21
Duplicate of #1178

Use latest dev build https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-04-13 02:21 UTC
Labels: bug
