### ISSUE TITLE
NPC deliver Paper bug

### ISSUE THREAD

**Issue by Garrarop** [PikaMug/Quests#787] opened 2019-05-10 05:03 UTC
This cannot be seen in the "/quest"
![quest](https://user-images.githubusercontent.com/30799098/57503656-6cbe9b00-72c7-11e9-8ae6-57b4da6cee10.png)
![questyml](https://user-images.githubusercontent.com/30799098/57503657-6d573180-72c7-11e9-80c9-76e5e16e5b74.PNG)
![questjournal](https://user-images.githubusercontent.com/30799098/57503659-6d573180-72c7-11e9-8ded-0d79fbc1f8f8.PNG)
PD: In the "quests journal" the name of the items don't translate

**Comment by PikaMug** [comment] 2019-05-10 05:21
This is not a bug. Translations only work in chat.

**Comment by Garrarop** [comment] 2019-05-10 16:56
That was not the problem, that was just a postscript. (Sorry Spanish PD = English PS).
The problem is that the paper does not appear in the quest.
Look at the first 2 images

**Comment by PikaMug** [comment] 2019-06-07 01:29
I created a single-stage quest to attempt to replicate this, but everything works fine:

![test](https://user-images.githubusercontent.com/2267126/59076035-d9ff2500-88a1-11e9-8284-02fcf3d409ce.png)
![test2](https://user-images.githubusercontent.com/2267126/59076100-32cebd80-88a2-11e9-82b8-e255ee9a270f.png)


Since you haven't provided a Quests version or sample quest using Pastebin, I must close this ticket. Feel free to provide that information in order to reopen the ticket.

**Closed by PikaMug** 2019-06-07 01:29 UTC
Labels: bug
