### ISSUE TITLE
Bring Item to NPC ignore lore

### ISSUE THREAD

**Issue by xxSmuffixx** [PikaMug/Quests#2133] opened 2023-07-06 19:39 UTC
### What does your feature do?

I'm using MMOItems. There you get custom items with many NBT Tags, like UUIDs and item lore which is hard to transfer to Quests.

![image](https://github.com/PikaMug/Quests/assets/52321608/ad47cdb4-75ca-4c2c-a295-3b5718402dac)

It would be great, if there'd be an option to ignore NBT stats and/r lore.

### How would people use it?

people who are using MMOitems would love to use it, because then they easy could use Mob drops as quest goals

**Comment by PikaMug** [comment] 2023-07-06 22:31
Duplicate of #1998 

https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features

**Closed by PikaMug** 2023-07-06 22:31 UTC
Labels: enhancement
