### ISSUE TITLE
New Quests not saving

### ISSUE THREAD

**Issue by Castiella** [PikaMug/Quests#1573] opened 2021-01-16 17:34 UTC
**What is your Quests version / build number (do _not_ say "latest")?**4.0.0-rc.4

Since updating to the new version, no new quest data will save upon /questadmin reload.

For example, we made the quest "Iron man" but whenever you edit the quest in any way (set an npc or rewards ect) and save, then do /questadmin reload - the quest edits you made are not there. 

Please find below my config

**Comment by Castiella** [comment] 2021-01-16 17:39
https://pastebin.com/Dt8i9Rfx

**Comment by DeadlykillOfficial** [comment] 2021-01-16 20:04
You need to provide exact build of your rc.4 version

**Comment by PikaMug** [comment] 2021-01-16 23:29
@Castiella Thanks for the report. Do you have any console errors to share?

Also consider trying the latest development build https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by Castiella** [comment] 2021-01-18 19:22
Hi there,

so far I have tried

 That dev build.
Removing MythicMobsExtention
Completely resetting Quests and doing a fresh install
Installing new citizens build

none of this has worked and this issue only started happening when i started using the new build on spigot.

Server Version:
>....=>.... [19:15:06 INFO]: This server is running Tuinity version git-Tuinity-"1d169e7" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Server Log:

[latest (3).log](https://github.com/PikaMug/Quests/files/5832051/latest.3.log)

if you want the log in pastebin form i can dooo

**Comment by DeadlykillOfficial** [comment] 2021-01-18 19:24
Could you provide the .yml data files of the people that lost their progress. Briefly explaining what kind of data has been lost.

**Comment by Castiella** [comment] 2021-01-18 19:39
Nobody lost progress. The quests wont appear in /quests editor when you do /questadmin reload.

**Comment by Castiella** [comment] 2021-01-18 19:39
Nobody can even take the quest as its almost like its instantly deleted upon /questadmin reload

**Comment by DeadlykillOfficial** [comment] 2021-01-18 19:42
In your log it does say "[Quests] Loaded 4 Quest(s), 8 Action(s), 1 Condition(s) and 809 Phrase(s)"

**Comment by Castiella** [comment] 2021-01-18 19:43
Yes. As I said, when you create a quest, and save and close, then do /questadmin reload it deletes completely as if you never made it.

**Comment by DeadlykillOfficial** [comment] 2021-01-18 19:46
I do see in your initially provided Quests.yml
That Iron Man quest exists in it. So if the problem is quests not loading properly. This is most likely because there is error in reading the quests. Most common one is Itemstacks issues.

**Comment by Castiella** [comment] 2021-01-18 19:46
Those are the default Quests within the plugin

**Comment by DeadlykillOfficial** [comment] 2021-01-18 19:47
I do see `Iron man` inside of https://pastebin.com/Dt8i9Rfx what you provided above?

**Comment by Castiella** [comment] 2021-01-18 19:48
Yes, because its a default quest within the plugin. We never removed it.

**Comment by DeadlykillOfficial** [comment] 2021-01-18 19:49
If it was default quest. It's name would've been default1-2-3. Instead it's called Custom.

**Comment by Castiella** [comment] 2021-01-18 19:49
Okay, then explain why when I completely deleted the Quests folder, that quest appeared again upon restart.

**Comment by DeadlykillOfficial** [comment] 2021-01-18 19:51
Also do you use QuestsGUI to save or just regular chat commands.
Whenever you save do you get Quests do you get message prompt to "/qa reload" also do you have any errors ?
Those are the Quest default quests: https://pastebin.com/jUYKk8eb - One of them is called "Iron Miner" not "Iron man" 
Line 838 at https://pastebin.com/Dt8i9Rfx
You can compare that it has nothing to do with default quest.

**Comment by Castiella** [comment] 2021-01-18 19:53
https://pastebin.com/yhbRyVcf 

This is our current config, fresh install as of 30 mins ago.

I save via QuestGUI and then do /questadmin reload as the docs say to do. 
There are no errors at all at the moment. 

The initial config I provided was before I deleted the entire folder and did a fresh instal - the issue is still persisting so whatever is in the original configis irrelevant. 

I've used Quests for over 5 years and have not had any issues like this.

**Comment by DeadlykillOfficial** [comment] 2021-01-18 19:54
Do you receive the message "Please use /questadmin reload" after you save or you do not?

**Comment by Castiella** [comment] 2021-01-18 19:54
yes

**Comment by Castiella** [comment] 2021-01-18 19:54
Would you like me to screen record the process so you can see?

**Comment by DeadlykillOfficial** [comment] 2021-01-18 19:54
Could you contact me in Discord?

**Comment by PikaMug** [comment] 2021-01-18 22:34
Closing as this conversation appears to have been taken private.

If this issue is not resolved, consider making sure that the Quests folder has write permissions. Follow [these steps](https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting) for the /plugins folder (ignore the mentions of languages files).

**Comment by DeadlykillOfficial** [comment] 2021-01-18 22:35
Sadly he never contacted me to get his issue investigated properly :(

**Closed by PikaMug** 2021-01-18 22:34 UTC
Labels: bug

**Comment by Castiella** [comment] 2021-01-22 09:22
Didn't contact as I havent had wifi for days.

However, I have just found removing QuestGUI fixes the problem. The issue seems to be with QuestGUI not saving the quests when you click save. 

I am using the most recent spigot build. 

QuestsGUI-0.24.jar
Using Quests-4.0.0-rc.4

**Comment by Castiella** [comment] 2021-01-22 09:23
https://pastebin.com/GnNxB90d here is my quests gui config, i'm just about to downgrade questgui builds to see if the issue fixes.

**Comment by DeadlykillOfficial** [comment] 2021-01-22 10:19
You clearly did not read the update description of QuestsGUI updating from 0.23 to 0.24 requires a regeneration of QuestsGUI files. This is the reason why it doesn't save them. Regen config files and it should be working fine

**Comment by Castiella** [comment] 2021-01-22 10:22
I did regenerate the files.... I completely deleted the folder.

**Comment by DeadlykillOfficial** [comment] 2021-01-22 11:07
Then it should be working quite fine
I've tested this myself once it was released. There was incompatibility with questsGUI and rc.4 because initial action was removed and all Input numbers were pulled with -1. That's why basically Save was exit and exit was doing nothing.

**Comment by DeadlykillOfficial** [comment] 2021-01-22 11:07
Worst case scenario if it didn't works. Can you send me picture of QuestsGUI editor ingame. I want to see how the ItemStacks are placed

**Comment by PikaMug** [comment] 2021-01-22 21:33
All issues with QuestsGUI are to be reported at https://www.spigotmc.org/threads/questsgui-paid.399346/
