### ISSUE TITLE
MySQL or I don't know error but nothing just "Plugin is loading..."

### ISSUE THREAD

**Issue by WhiteFrost06** [PikaMug/Quests#1770] opened 2021-08-12 21:09 UTC
Hello!

I use your plugin since so many years now and I decided to make a bungee server with 2 roleplays servers connected between my hub and I have the plugin only on my 2 rp servers. I just try to make modifications on my actually quests but I can't on any servers because the plugin is loading with your famous sentence. So how can I make the plugin work? Please, by advance, you're greatest supportert! (I have also QuestGUI on both).

Greetings!

**Comment by DeadlykillOfficial** [comment] 2021-08-12 21:11
Quests doesn't support Bungee at all.
MySQL support it's not fully done yet. Either way.
If you plan to make 2 servers. You need to have exactly same locations, npcs, everything copied aka Duplicate of the server in order to EVENTUALLY work.
Since Bungee ain't supported it would most likely not work as you think it should.
"Plugin is loading" because it errors out in your console.

**Comment by WhiteFrost06** [comment] 2021-08-12 21:16
Ok so If I remove the NPCs and the quests which are not on the good positions it will be worked? Then I ask the question: If I'll do this, I can hope XP and so many rewards about quests will be work even If I have stats of others plugins connected because I suceed to make quests already present but failed to use commands because errors like you said!

**Comment by WhiteFrost06** [comment] 2021-08-12 21:53
Bro I removed quests and config.yml nothing changed, maybe delete all datas to be work?

**Comment by DeadlykillOfficial** [comment] 2021-08-12 21:55
Trial - Error it. Eventually you will either get it working nor won't.
Officially Quests does not support Bungee and cross-servers.

**Comment by WhiteFrost06** [comment] 2021-08-12 22:05
I removed all the folder from both servers, reboot then it works! I changed the config.yml like before, I put my old quests and it work! I'm happy, thanks!

**Closed** 2021-08-12 22:05 UTC
