### ISSUE TITLE
Item requirements do not work (able to use other tools to achieve object) + bugs

### ISSUE THREAD

**Issue by AadilF1** [PikaMug/Quests#1218] opened 2020-04-17 22:49 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.2

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
In the default quest 'Iron Miner', If I try mining a block with other pickaxes, I'm still able to complete the quest, even though the required item is a stone pickaxe. Similar for other quests I created, for example, kill 2 pigs with an iron sword, I'm able to kill those pigs with a diamond sword. When I look at the requirements menu, it says (none set), even though the default quest Iron miner says a stone pickaxe is required, or when I try to add an item, I'm able to add it, and save it, but when I go back into the requirements menu it says (none set) again, even though I've saved and reloaded it. Also when I do /quest iron miner, it says requirements: but doesn't say anything beyond that.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

An example is the default quest Iron Miner.

**Comment by PikaMug** [comment] 2020-04-18 03:36
Duplicate of #1207 

Use latest dev build https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-04-18 03:36 UTC
Labels: bug
