### ISSUE TITLE
questbook ist very buggy

### ISSUE THREAD

**Issue by Paddiii-Pixeltopia** [PikaMug/Quests#2024] opened 2022-11-01 22:11 UTC
### What is your Quests version / build number (do *not* say "latest")?

4.6.0-b361

### Describe the problem and how to replicate it.

Not all tasks are displayed in the quest book, only as many as fit on one book page

### Any console errors to share?

```shell
no
```

**Comment by Paddiii-Pixeltopia** [comment] 2022-11-01 22:19
![image](https://user-images.githubusercontent.com/71345116/199352736-9bc4c0fd-c7dc-46c8-ba31-0c552acfc53e.png)

**Comment by PikaMug** [comment] 2022-11-02 05:37
Duplicate of #1946

**Closed by PikaMug** 2022-11-02 05:37 UTC
Labels: bug
