### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1263] opened 2020-04-28 01:23 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.3 B107

Got some error message

![image](https://user-images.githubusercontent.com/61608872/80436179-1fe92f80-8931-11ea-8abc-d0f8e3f9eaa2.png)
![image](https://user-images.githubusercontent.com/61608872/80436356-8a9a6b00-8931-11ea-8b1b-e6704c7e4498.png)
![image](https://user-images.githubusercontent.com/61608872/80436424-aaca2a00-8931-11ea-8281-d96b75dfd811.png)

error log :
https://pastebin.com/a3jMf4yh
Full quest:
https://pastebin.com/EUM28s8M

**Comment by PikaMug** [comment] 2020-04-28 03:48
Duplicate of #1233 

Use latest development build https://ci.codemc.io/job/PikaMug/job/Quests/

**Closed by PikaMug** 2020-04-28 03:48 UTC
Labels: bug
