### ISSUE TITLE
3 bugs (Java, Events, and Questadmin reload) From last versions of quests.

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#851] opened 2019-07-16 01:20 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

Both 3.7.5 and 3.7.6-1 Beta (Same problem)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Many problems with thoses versions ...

1: If i do a "/questadmin reload" when player have for example 'Quest 1', then he can take the 'Quest 1' again with the PNJ even if he ALREADY HAVE Quest 1 ... so he have it twice, and i can't "/questadmin quit" his double bugged quest.

2: I don't know why, but the Event of the absolute first quest is called twice on the first stage.
Firstly, it's called at the begining of the quest (as it have to do)
Twicely, it's called one more time at the end of the stage (as it don't have to)

The event is easy, Command action at the begining of the quests that give to the player his journal.
But when the player end the quest, the journal is taken off. (Only 1 event, and the command is entered twice, once at the begining, and another one at the end of the stage ...)

3: Thoses versions are making some java errors, here we have:
```
03:02:37: Could not pass event NPCRightClickEvent to Quests v3.7.5
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:385) [citizens-2.0.16-SNAPSHOT.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1315) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_181]
at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_181]
at me.blackvein.quests.Quest.completeQuest(Quest.java:625) ~[?:?]
at me.blackvein.quests.Quest.nextStage(Quest.java:186) ~[?:?]
at me.blackvein.quests.Quester.finishObjective(Quester.java:1927) ~[?:?]
at me.blackvein.quests.Quester.interactWithNPC(Quester.java:1608) ~[?:?]
at me.blackvein.quests.listeners.NpcListener.onNPCRightClick(NpcListener.java:167) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
... 24 more
```
Ps: It looks like the java error occurs only when a player finish a quest.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

- Of course, here is the quest where the event is applied twice:
```
  custom10:
    name: Quêtes et combats
    npc-giver-id: 144
    ask-message: '§bInitiation aux quêtes et aux combats. §f[§cRewards: §9+400 Exp§f,
      §aZone 3§f]'
    finish-message: §e** §aZone 3 débloquée §e**
    gui-display: name-DIAMOND:amount-1
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 4
              data:
                Objective Name: §6(§4§M=§4 Monstres à tuer §4§m=§6) §c§lMouton appeuré                           §9(§3§m==§9 Restants §3§m==§9)       §1§l%count%
                Conditions: NONE
                TargetConditions: NONE
                Internal Mobnames: ANY
                Mob Level: '0'
                Mob Faction: ANY
                Notifier enabled: 'true'
                Notifier msg: §f[§a %c% §f] §6mobs tués sur §f[§c %s% §f]
          start-event: Commande
          start-message: '&eTriana: &bBienvenue aventurier, ce lieu a été conçu pour
            initier les nouveaux venus sur le fonctionnement des combats et des quêtes.
            Commence par consulter ton &d&lJournal&b que tu viens de recevoir!'
        '2':
          npc-ids-to-talk-to:
          - 144
          objective-override: §cRetourner voir §6§lTriana §cpour finaliser votre quête.
    rewards:
      commands:
      - rg addmember zone3 <player> -w Tutoriel
      - class exp <player> 400
      - questadmin give <player> Compétences des classes
      commands-override-display:
      - ''
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
```

- The Event 'Commande':
```
  Commande:
    commands:
    - mycmd-runas player <player> /journalquest
```

- And then the Mycmd-cmd:
```
QuestJournal:
  command: /journalquest
  type: RUN_COMMAND
  runcmd:
  - /quests journal
  permission-node: aides
  permission-error: 'Help incomming'
```

**Comment by tiradorus** [comment] 2019-07-16 11:55
Another bug with the version 3.7.5 (i imagine the same with 3.7.6)
Found this morning.

Events are sometimes not working ... that's all, for absolute no reason and no java errors.
on the quest bellow, the Event 'Iced' isn't called. Never.
I stay on 3.6.8 for the moment, quest 3.7.5 is unusable because of all of thoses bugs

Quest with the event ''bugged':

```
  Dps5:
    name: Les piliers protecteurs de ventura
    npc-giver-id: 29
    ask-message: '§bAllez briser les cristaux de glace §bdans §bles §bpetits §bpiliers
      autour de §bl''île §f[§cRewards: §9+650 Exp§f, §aEpee §aAndral§f]'
    finish-message: §e** §b+650 §9Expérience §e**
    gui-display: name-WOOD_SWORD:amount-1
    requirements:
      permissions:
      - ils.use.dps
      quests:
      - Pas de repos pour les vieux os
      fail-requirement-message: Vous n'êtes pas dps
    stages:
      ordered:
        '1':
          break-block-names:
          - PACKED_ICE
          break-block-amounts:
          - 4
          break-block-durability:
          - 0
          objective-override: §cBrisez la §9Glace §cau centre des piliers blancs qui se trouvent un peu partout autour de l'île
          start-message: '&eThalion: &bAh, tu es revenu, je vais avoir besoin de toi
            pour récolter les cristaux de glace nécéssaire à l''équilibre de l''île.
            Va voir pour récolter les cristaux protecteurs au centre des pilliers
            de bénédiction. Tu en trouveras tout autour de Ventura!.'
        '2':
          items-to-deliver:
          - name-PACKED_ICE:amount-4
          npc-delivery-ids:
          - 28
          delivery-messages:
          - Apportez ces pierres à <Npc>
          objective-override: §cRapportez les pierres à §6Anderion §cau centre de Ventura
          start-event: Iced              < ===================== This event won't start
        '3':
          locations-to-reach:
          - Ventura 97.0 112.0 46.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Instance de la crypte
          objective-override: §cAllez voir dans l'instance de la §4§lCrypte §cen §6[§d97,112,46§6]
          start-message: '&eAnderion: &bAh merci bien, c''est vrai que les cristaux
            sont gourmand en énergie. Tiens pendant que t''es là! On a peut-être trouvé
            la source des problèmes, au centre de l''île aux squelettes se trouve
            une crypte profonde, nous y avions enfermés les monstres trop dangereux,
            va voir ce qu''il s''y passe'
          complete-message: '&eAnderion: &bC''est bien ce qui me semblais, les cristaux
            semblent réagir à cet endroit. Ne tente surtout rien tout de suite, va
            rendre compte à &eFaena &bde la situation, elle saura quoi faire.'
        '4':
          npc-ids-to-talk-to:
          - 25
          complete-message: '&eFaena: &bLes cristaux sont donc bel et bien en rayonnance
            avec cette crypte, c''est étrange, le lieu a été scéllé il y a bien longtemps
            ... il faut impérativement aller voir ce qu''il se passe là-bas'
    rewards:
      commands:
      - mm items give <player> Epee_Andral
      - class exp <player> 650
      commands-override-display:
      - ''
```
I have a theory. for this bug.
**I have 3 same/different quests named:**
"Les piliers protecteurs de ventura"
"Les piliers protecteurs de ventura affaiblis"
"Les piliers protecteurs"
All of thoses quests are the same one, but for a different class (it's a quest for a defined class, with a different permission requirement)

Maybe if a quest have the same full name as another one, it create some problems (I don't had any problems on 3.6.8 or 3.0.1 ... and never had any problems with it since the 3.7.5)


And here is the Event **Iced**:
```
  Iced:
    items:
    - name-PACKED_ICE:amount-4
```

**Comment by PikaMug** [comment] 2019-07-16 20:17
I'm closing this as you've reported 4 bugs in 1 issue. Please limit to one per issue so as to stay on-topic.

Referencing your initial comment:
1. Duplicate of #811 this is intentional behavior
2. Duplicate of #838 this is already being worked on
3. Need more information, namely what you did to produce the error.

The fourth issue about Ice is probably related to #838

**Closed by PikaMug** 2019-07-16 20:17 UTC
