### ISSUE TITLE
add Step block on goal (reissue)

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1568] opened 2021-01-15 19:58 UTC
sorry for the repetition of my post but there was a slight misunderstanding.
#1550 
**What does your feature do?**

I wanted to add this functionality:
![1er](https://user-images.githubusercontent.com/74351200/104773588-9656e780-5775-11eb-946d-72b1a3256573.JPG)
**Define the step block**

In the stage objective, category "block" because despite all the proposed functions I would like the players to use a particular block at positions
![2eme](https://user-images.githubusercontent.com/74351200/104773602-99ea6e80-5775-11eb-9901-bb664237456a.JPG)
**Blocks**
![3eme](https://user-images.githubusercontent.com/74351200/104773618-9e168c00-5775-11eb-9006-c4bcd2af1c78.JPG)
**use blocks**

For example during an exploration of a cave the player must for example find a hidden skull in order to obtain a card (given by the function of the quests events) however if he clicks on any skull in the cave that he validate the step
But I want only one (whose block would be defined as selecting a starting block but directly integrated into the quest as a block objective) can make him accomplish that objective.
To select a step block, choosing like this is fine
![4eme](https://user-images.githubusercontent.com/74351200/104773631-a40c6d00-5775-11eb-9665-55dfff807e5b.JPG)
**_right click on the block to be used as a step block, then enter < finished > to save or < clear > to erase all data or < cancel > to return to the menu_**

And whose display of the lens would be on this principle
![Objectif](https://user-images.githubusercontent.com/74351200/104773423-555ed300-5775-11eb-9a22-598df17ea07a.JPG)
**define the replacement list of the objectives of the stage**

I hope I was clear on this idea which would help me enormously.
Your plugin is wonderful, I hope my idea will benefit many enthusiasts like me

**Comment by PikaMug** [comment] 2021-01-15 21:56
Duplicate of #1550 

While I appreciate the detailed explanation, it's my understanding you simply want to convince a player to step on a certain block. Install [WorldGuard](https://enginehub.org/worldguard/) (not affiliated) and create a 1x1 area around the block to step on. In Quests, if you would like to do this at the start of a quest, use the _Set region start (Définir la région)_ selection. If you would like to do this during a stage, use the _Reach locations (Atteindre des coordonnées)_ objective.

**Closed by PikaMug** 2021-01-15 21:56 UTC
Labels: enhancement
