### ISSUE TITLE
Non-Block/Mob specific quests.

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#803] opened 2019-05-23 21:32 UTC
**What does your feature do?**
I want there to be the option to not have to select specific blocks or mobs, in Blocks or Mobs quests.

**How would people use it?**
People would be able to use it for quests where players have to mine for example; 1000 blocks. But they can be any block, and don't have to be a specific one. Same for mobs, they can kill any mob, doesn't have to be a specific set type.

**Comment by PikaMug** [comment] 2019-05-24 13:33
Partial duplicate of #789 (blocks, not mobs)

**Comment by AtomixCM** [comment] 2019-05-24 18:26
Hey Pika, do you have any intentions on adding this functionality? Right now, it makes or breaks me using Quests...

**Comment by PikaMug** [comment] 2019-07-01 20:37
I've determined that this is best left to a custom module. Please see https://github.com/PikaMug/Quests/issues/789#issuecomment-507416132

**Closed by PikaMug** 2019-07-01 20:37 UTC
Labels: duplicate, enhancement

**Comment by Technodate** [comment] 2019-07-01 21:13
Since you closed my request. I might have an alternative, ofc idk if it'll be any easier or not.

But what if players would be able to create their own "Blocknames"
Those blocknames would be displayed in another file, where players can create a list of what blocks are selected. Kind of like a placeholder I suppose.

Here's an example (If it helps in any way x.x)

      break-block-names:
      - STONESET
      break-block-amounts:
      - 10000
      break-block-durability:
      - 0

In this case the block name would be STONESET, which refers to a list.
name: STONESET
blocks:
      - STONE, 0
      - STONE, 1 (these would be dmg values, would of course also be possible to add in a different way if that's easier.)
      - COBBLESTONE
      - STONEBRICK, 0
      - STONEBRICK, 1

This list is named; "STONESET" and upon adding it into the stage editor. The stage editor will accept any of the displayed blocks that are written by the user in a different list.
Again, not sure if this is any easier to do, but if it would be possible then I'd love to see it.

**Comment by PikaMug** [comment] 2019-07-01 21:43
@Technodate Please read my linked comment in the last post. Part of the issue was that, because of how the plugin is structurred, we can't just put anything for the block name. It has to be a valid name from the [Bukkit Material list](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html).
