### ISSUE TITLE
Error spam (1.12.2)

### ISSUE THREAD

**Issue by ducdzz61** [PikaMug/Quests#1444] opened 2020-11-08 01:54 UTC
link: https://hastebin.com/izupixakoz.properties
ver server: paperspigot 1.12.2
ver pl: Quests v4.0.0-rc.2-b158 (download by https://github.com/PikaMug/Quests/issues/1435)

from the time I used the quests plugin until now all versions have bugs with 1.12.2
Can you fix it please? I have been waiting for several months to use it but still have continuous errors

**Comment by ducdzz61** [comment] 2020-11-08 01:55
Please state the error if it's my fault

**Comment by PikaMug** [comment] 2020-11-09 18:03
Thanks for the report. This appears to be a duplicate of #1439 which is not specific to 1.12 versions. Please give the following development build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/163/

**Closed by PikaMug** 2020-11-09 18:03 UTC
Labels: bug
