### ISSUE TITLE
Problem with softdepend (Parties plugin)

### ISSUE THREAD

**Issue by MisterLolxd2** [PikaMug/Quests#2079] opened 2023-03-10 20:50 UTC
### What is your Quests version / build number (do *not* say "latest")?
4.8.0-b395
Parties: 3.2.9
Server: Paper 1.16.5
Java: 17

### Describe the problem and how to replicate it.

1. The problem is that if two players are on the same team and take the quests (use-parties-plugin: true) then the progress is double-studded. Player A will kill player B, then instead of progress to be 1/50 it is 2/50, 4/50, 6/50... If there are three, it is triple etc.
The second similar to the one described above is that if player A from the clan takes the quest and kills someone, the progress is 1/50, while if player B from the same clan will take the same quest and kill someone then it will be a progress of 3/50, because it doubles the progress and adds what was with the first one (player A), therefore there is a great punching and basically a mess ... And it should add to each one individually without "leveling out the progress".

2. If player A and B from the same clan takes the quest from use-parties-plugin: true and the second use-parties-plugin: false and player A kills someone, it also charges progress to player B and double player A ;/

Sorry for my english.

### Any console errors to share?

```shell
None of errors.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
If you need it, I'll send it.
```

**Comment by PikaMug** [comment] 2023-03-10 21:58
@MisterLolxd2 Thanks for the report. Do you have any of the following plugins installed?

- DungeonsXL
- mcMMO Overhaul (not the free version)
- Party and Friends Extended for Spigot
- SimpleClans

If so, does temporarily removing the plugin fix the issue?

**Comment by MisterLolxd2** [comment] 2023-03-10 22:07
No, i have only Parties and addon to the Parties (LastLoginApi).

**Comment by PikaMug** [comment] 2023-03-10 23:20
Alright, could you set `console-logging: 4` in your _config.yml_ file and share the console output you get from replicating the problem?

**Comment by MisterLolxd2** [comment] 2023-03-10 23:55
This?

[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-1 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-2 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-3 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-4 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-5 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-6 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-7 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-8 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-9 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-1 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-2 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-3 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-4 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-5 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-6 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-7 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-8 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-9 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-2 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-1 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-2 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-3 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-4 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-5 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-6 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-7 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-8 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-9 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-1 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-2 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-3 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-4 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-5 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-6 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-7 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-8 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-9 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
[00:54:58] [Craft Scheduler Thread - 330/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 339/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 338/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-dostarcz-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-2 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-3 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-4 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-5 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-6 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-7 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-8 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-kopalnia-klanowe-9 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
[00:54:59] [Craft Scheduler Thread - 314/INFO]: [Quests] Found 1 party members for quest ID zadanie-pvp-klanowe-2 via Parties plugin

**Comment by MisterLolxd2** [comment] 2023-03-10 23:58
Its really spaming every time, if i killed someone with "parties quest" nothing "special" sends.

**Comment by MisterLolxd2** [comment] 2023-03-11 00:00
From what I can see, it is sent with every move. In motionless when I killed someone, this particular task was repeated 

[00:59:37 INFO]: Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
 [00:59:37 INFO]: Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
 [00:59:37 INFO]: Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin
 [00:59:37 INFO]: Found 1 party members for quest ID zadanie-pvp-klanowe-1 via Parties plugin

**Comment by PikaMug** [comment] 2023-03-11 04:06
@MisterLolxd2 Thanks for following up. Please try https://ci.codemc.io/job/PikaMug/job/Quests/396/

**Comment by MisterLolxd2** [comment] 2023-03-11 19:56
The problem of leveling out progress remains. If player A and B are from the same clan and have the same quest, but different progressions, e.g. Player A 0/30 and Player B 5/30, then after killing the player they have 6/10 (Player A and B).

**Comment by PikaMug** [comment] 2023-03-11 20:35
> The problem of leveling out progress remains. If player A and B are from the same clan and have the same quest, but different progressions, e.g. Player A 0/30 and Player B 5/30, then after killing the player they have 6/10 (Player A and B).

Should be fixed with https://ci.codemc.io/job/PikaMug/job/Quests/397/

> And the If player A and B from the same clan takes the quest from use-parties-plugin: true and the second use-parties-plugin: false and player A kills someone, it also charges progress to player B - BUT IN MINING (I suppose in all kinds this is the case) in PVP its fixed.

Will need to see example quests to replicate this (please use a site like Pastebin).

**Comment by MisterLolxd2** [comment] 2023-03-11 20:37
https://pastebin.com/Rf8nDezv

**Comment by PikaMug** [comment] 2023-03-11 23:35
@MisterLolxd2 Thanks, but I wasn't able to replicate that issue on the dev build 397. Which of those quests are the two you used?

**Comment by MisterLolxd2** [comment] 2023-03-11 23:59
"zadanie-kopalnia-1" used player B ( use-parties-plugin: false)
"zadanie-kopalnia-klanowe-1" used player A ( use-parties-plugin: true)

And i see another bug, If only one person from the clan (player A) has a quest, the other person (player B) does not count the progress to the quest for player A, e.g. player B kills someone, it does not add it to the progress of the quest for player A

**Comment by PikaMug** [comment] 2023-03-12 04:12
> "zadanie-kopalnia-1" used player B ( use-parties-plugin: false) "zadanie-kopalnia-klanowe-1" used player A ( use-parties-plugin: true)

I tried using those quests, but am still not seeing any issues. Killing a player does not increment "mining" (break block) objectives, whether it's A killing B, or B killing A. 

> And i see another bug, If only one person from the clan (player A) has a quest, the other person (player B) does not count the progress to the quest for player A, e.g. player B kills someone, it does not add it to the progress of the quest for player A

That sounds like expected behavior depending on how `use-parties-plugin` and `same-quest-only` are set.

**Comment by MisterLolxd2** [comment] 2023-03-12 16:48
1. I explained it wrong. My bad english... I mean:

If player A and B from the same clan takes the quest from use-parties-plugin: true and the second use-parties-plugin: false and player A mining ex. stone, it also charges progress to player B.

2. But:
    options:
      use-parties-plugin: true
      same-quest-only: false

**Comment by PikaMug** [comment] 2023-03-13 02:55
If I understand correctly, you're saying that both players A and B (in the same clan/party) each have the `zadanie-kopalnia-1` and `zadanie-kopalnia-klanowe-1` quests, and that breaking stone progresses both quests for both players. But this doesn't happen for me—player A gets progress in both quests, while player B only gets progress in `zadanie-kopalnia-klanowe-1` because _use-parties-plugin: true_ for that quest.

**Comment by MisterLolxd2** [comment] 2023-03-13 15:53
Hm, I'll check again.

**Comment by PikaMug** [comment] 2023-03-19 02:49
Feel free to create a new issue should the problem reemerge.

**Closed by PikaMug** 2023-03-19 02:49 UTC
Labels: bug
