### ISSUE TITLE
Recent bug founds

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1477] opened 2020-11-28 23:26 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
Quests rc.3-b168
QuestsGUI v0.22
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

The following issues are:
1.QuestsGUI no longer automatically attach quests to the NPC  and opens up a GUI on player right click when quest attached to NPC. Same mechanics seems to work about right on rc.2-157 with v0.21 questsGUI.

2.Error called `lastknownname` being null after every usage of MySQl query by Quests. 

3.Every Interaction with NPC being part of any Quest seems to send repetetive message over and over.
https://prnt.sc/vs0usr - Picture of the situation. This picture is being send at any interaction with the NPC. regardless just no quests available, progress to stage or any other interaction.

**Comment by DeadlykillOfficial** [comment] 2020-11-29 01:53
Quicker update after further testing it turns out that error 3. is caused by some weird interactions between Quests and Citizens. But was able to fix that issue from Citizens itself only. Issue 1. and 2. still remain bugs.

**Comment by PikaMug** [comment] 2020-11-29 02:09
Thanks for the report!

1. Please update to QuestsGUI 0.22
2. Duplicate of #1475 please use https://ci.codemc.io/job/PikaMug/job/Quests/169/
3. That doesn't look like a message from Quests. Pretty sure that's Citizens formatting.

**Closed by PikaMug** 2020-11-29 02:09 UTC
Labels: bug
