### ISSUE TITLE
New Error Code when Player Joined with a Preexisting Quest active

### ISSUE THREAD

**Issue by TheDilPickle** [PikaMug/Quests#1197] opened 2020-04-14 01:02 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.3 b99
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**.    When this player joined after having this quest active it threw back these errors in the console.  This did not happen back on build 3.8.8.  https://pastebin.com/e0HC8p2H

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/XkCpKq3U.   Another thing I would like to add.  Whenever you do a delivery to an NPC and set the messages correctly in game in the editor it them spams hundreds of them in the actual quest file.  Not sure if that is suppose to happen.  You can see it in that pastebin.

**Comment by PikaMug** [comment] 2020-04-15 09:05
Duplicate of https://github.com/PikaMug/Quests/issues/1191

Use https://ci.codemc.io/job/PikaMug/job/Quests/101/

**Closed** 2020-04-15 09:06 UTC
Labels: bug, duplicate
