### ISSUE TITLE
Add support permission for separate worlds.

### ISSUE THREAD

**Issue by Castiella** [PikaMug/Quests#1328] opened 2020-06-18 14:47 UTC
I need to block players from completing Quests in certain worlds. We have a creative world, and even with every quests permission negated in that world they can still complete a quest in there.

**How would people use it?**
Something like a Quests.Complete permission that can be negated. For example, if a quest is to break 100 gold ore, and they go into the creative world and break 100 ore there, it won't allow them to as they have the permission to complete/do a quest in that blocked world.

Hope this makes sense, thank you!

**Comment by PikaMug** [comment] 2020-06-18 19:35
Duplicate of #839

**Closed by PikaMug** 2020-06-18 19:35 UTC
Labels: enhancement
