### ISSUE TITLE
what i have to do, if a quest should work once per day? reset at midnight (cause its a new day)

### ISSUE THREAD

**Issue by wotnurwasfrage** [PikaMug/Quests#2145] opened 2023-09-08 19:51 UTC
### Where else have you looked for answers to this question?

https://pikamug.gitbook.io/quests/beginner/planner

### Share your question with as much detail as possible.

i would like to get a quest start, once per day, also a daily quest (maybe weekly, monthly)
a new day begin after midnight.
so, what i have to do for? have i done something mistakes in the quest.yml below?..

the point is:
if i dont set any date with the planner, the particles stop when i have taken the quest. if i set a date with the planner, it never stops to make particles, equal if i have a cooldown.. shouldnt it finally bring the particles when the quest is avaible for me? (every client different?)
and, my main problem is: the cooldown in case of "override: true" dont looks to work, i can get the same quest on multiple times, not just once per day..

my wish is: that users can take the quest 23:00 and 00:01 again, cause its a new day in the calendar, but both, once per day, equal at which time they like to do it. (if on 16:00 and next day on same time is equal, or just few minutes before midnight, and after midnight again)

i dont find out what i made wrong :c
cause the override: true should make that the cooldown on same day is active, but should be clear when a new day begins, right?
i tried out if i make 86000 seconds than with 86400 seconds, if there could be a conflict, but it dont changes..

//////////////////////////////////////////////

custom1:
    name: firstday
    ask-message: Aufgaben erledigen um punkte verdienen.
    finish-message: Gut gemacht, 
    npc-giver-uuid: 34d1292f-e7b5-4d25-9a45-71180213977a
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - ddfe7d11-f8b3-4ad2-a59a-130f25ef864c
          start-message: Bitte geh in den Team-Raum(HoF) und melde dich beim Owner.
          complete-message: Oh, ein Neuling, Willkommen an Bord. Melde dich nun wieder beim Ausbilder
            für weitere Arbeit.
        '2':
          npc-uuids-to-talk-to:
          - 34d1292f-e7b5-4d25-9a45-71180213977a
          complete-message: Gut gemacht, du hast dir 1 punkt verdient. Komm Morgen
            wieder, dann habe ich dir weitere Aufgaben.
    rewards:
      commands:
      - points give <player> 1
    planner:
      start: 8:8:2023:0:0:0:Europe/Berlin
      end: 8:8:2023:23:59:59:Europe/Berlin
      repeat: 86400
      cooldown: 86400
      override: true
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true

**Comment by wotnurwasfrage** [comment] 2023-09-09 23:24
okay, i found it now, it, "works", but, i get the offer to accept the redo quest, while i have the cooldown for the rest of the day... and the redo particles are over it. (and also the followed day has the particle from redo-quest)
should this not comes earlier? should the system not see before i click the quest guy and accept the quest, that i cant start the quest?
or can i set this anyway in the configs?

and also the followed day has the particle from redo-quest
shouldnt this reset at the next day?

i mean:
so, a user cant see if he can start the quest, cause the cooldown dont react before speakin, and cause also the next day is marked as redo quest, i cant just make off the redo particles..
i just dont have particles if the quest dont has a repeat.. but, then i cant start it again... thats, not the sense i search..
can i config them anyway? or is there an api for it?

i think there should be a more obviously way a user can see if he can start a quest. but, cause i think its all there, i think i just make something wrong...
i mean: if the "repeat" particles finally come when "cooldown" is over, and the quest can get accepted after same "cooldown" ends, it would looks like -> 
particle 1= a quest can get started first time (or just onetime)
particle 0= no quest can get started (0 cause there is just 1 and 2 with a particle)
particle 2= the quest can repeated now

cause this plugin is developed so much years and its realy good one (maybe the best) i think this is inside the long time, but i just made something wrong :c (cause what i wish is so much easy, so its more likely my fault or a bug..)

**Comment by PikaMug** [comment] 2023-09-11 21:54
Duplicate of #2137

> okay, i found it now, it, "works", but, i get the offer to accept the redo quest, while i have the cooldown for the rest of the day... and the redo particles are over it. (and also the followed day has the particle from redo-quest)
should this not comes earlier? should the system not see before i click the quest guy and accept the quest, that i cant start the quest?
or can i set this anyway in the configs?

This is so that players can see how much time is left before the quest is available on NPCs with multiple quests.

There are no plans to change the particle system, but you could try [QuestsEffect](https://pikamug.gitbook.io/quests/casual/bridge-plugins#questseffect) and, if it doesn't do what you need, suggest new functionality for that instead.

**Closed by PikaMug** 2023-09-11 21:54 UTC
Labels: question
