### ISSUE TITLE
/quest

### ISSUE THREAD

**Issue by DenisJ9798** [PikaMug/Quests#755] opened 2019-03-29 00:12 UTC
How do I make 'start-message' appear when viewing active quests? (can be when you hover your mouse over the quest)

**Comment by PikaMug** [comment] 2019-03-29 00:19
Possible duplicate of #754

You can’t. The start message is only shown when you’ve started that quest/stage.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by PikaMug** 2019-03-29 00:19 UTC
