### ISSUE TITLE
Dialogue per stage

### ISSUE THREAD

**Issue by Kayndashians** [PikaMug/Quests#1653] opened 2021-03-19 11:34 UTC
**What does your feature do?** it would be amazing if we could add a dialogue per stage, it'll give us more options to make stories and add life to the quest itself

**How would people use it?** when creating a new stage, you would have the option to add a dialogue once that stage ends

**Comment by PikaMug** [comment] 2021-03-20 01:32
Duplicate of #1062

**Closed by PikaMug** 2021-03-20 01:32 UTC
Labels: enhancement
