### ISSUE TITLE
bungeecord/waterfall/multiverse support

### ISSUE THREAD

**Issue by Qfrijters** [PikaMug/Quests#1367] opened 2020-07-27 14:30 UTC
**What does your feature do?**
Someone else had asked this, but I was wondering if there would be a possibility to add support for bungeecord/waterfall so you can do quests that take place over 2 servers. OR multiverse support. This would be very nice for mmorpg servers.

**How would people use it?**
Well, it might expand features where you can from one world to another to continue the quest. mmorpg server will probably benefit from this.

**Comment by PikaMug** [comment] 2020-07-27 19:22
Essentially duplicate of #312

**Closed by PikaMug** 2020-07-27 19:22 UTC
Labels: enhancement
