### ISSUE TITLE
npc-uuids-to-talk-to does not allow players to talk when hand have item

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1973] opened 2022-06-18 05:37 UTC
### What is your Quests version / build number (do *not* say "latest")?

[13:36:44 INFO]: Quests 4.4.3-b343
[13:36:44 INFO]: 建立者 ： Blackvein 接任者 ： PikaMug & contributors
[13:36:44 INFO]: https://github.com/PikaMug/Quests

### Describe the problem and how to replicate it.

i have
```
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - 454c13bd-93dc-4293-9324-09ad2bb26c47
```

if i have item in my hand, i cannot talk to the npc

### Any console errors to share?

```shell
no error
```

**Comment by PikaMug** [comment] 2022-06-18 10:44
This did not happen for me when talking to a Citizens NPC with a slime ball in hand (created my own quest since you did not provide an example). Perhaps your NPC has other functionality that is affecting this (being used as a start/delivery NPC or other plugin integrations).

**Comment by hkkongou** [comment] 2022-06-20 06:55
> This did not happen for me when talking to a Citizens NPC with a slime ball in hand (created my own quest since you did not provide an example). Perhaps your NPC has other functionality that is affecting this (being used as a start/delivery NPC or other plugin integrations).

I think I have some idea after testing.

The item that I am holding is from MMOITEMS, when holding it, I cannot right click to npc and finish the objective, but i don't know why it works like this

Other plugin seems fine.

**Comment by PikaMug** [comment] 2022-06-20 12:00
So then this would be a duplicate of #1935 

#1929 might resolve this but there has been no progress.

**Closed by PikaMug** 2022-06-20 12:00 UTC
Labels: bug
