### ISSUE TITLE
getting "Null" when player tries to accept quest.

### ISSUE THREAD

**Issue by MrRayhonda** [PikaMug/Quests#998] opened 2019-11-09 18:41 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

3.8.1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

[Quests] RiplyGamer attempted to take quest "null" but something went wrong

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/5DqFMJrU

Hey sorry to bug you again, I gave the general default player group all the non admin perms for questing but they still cannot accept the quest when prompted yes or no. I am able to do them though (as op and admin) but not players.

**Comment by MrRayhonda** [comment] 2019-11-09 18:43
addition/edit: It's only happening for old man jenkin's gimme bacon quest. Elgrog's iron ore quest works (but that was the pre made quest) I'm still unsure what I did wrong.

**Comment by PikaMug** [comment] 2019-11-11 20:25
I have not been able to replicate this in my test environment with the correct permissions, but will continue to investigate and update accordingly.

![gimme](https://user-images.githubusercontent.com/2267126/68618514-7d7ae400-0497-11ea-8593-1c253c021a8c.png)

**Comment by MrRayhonda** [comment] 2019-11-11 20:35
huh interesting o,o  the issue didn't occur to me when I did it but it did happen when a default player tried to do it though if that helps at all. :D

**Comment by PikaMug** [comment] 2019-11-14 19:41
Duplicate of #993

**Comment by PikaMug** [comment] 2019-11-24 07:27
@MrRayhonda Would you be able to provide the following information? Myself and another collaborator are still investigating this.
- Operating system (Windows/Mac/Linux)
- Major Java version (Java 8, Java 11, et al.)
- Permissions plugin and version

**Comment by MrRayhonda** [comment] 2019-11-24 07:44
@PikaMug Sure thing!

Windows 10

The java thing I'm not sure how to check. Do you mean on my pc that I have installed or on the server? The Server.jar is the Paper server for 1.14.4 (not entirely sure how to check any more info on that) and my PC java version is version 8 update 181

MC Version is 1.14.4

LuckPerms 4.4.1 for permissions

**Comment by PikaMug** [comment] 2019-11-24 08:00
Thanks for that!

I meant on the server that you're running Quests on. On a Windows server, a great way to check for Java is to open a new Command Prompt and type `java -version` then hit Enter. It may show a lot of information, but all we need is the version number.

**Comment by MrRayhonda** [comment] 2019-11-24 08:10
Np! Sadly the server isn't hosted on my computer. I have this pterodactyl back end thing I use that my friend set up to get the server hosted etc. I'm totally new to this and use my pc for work but wanted a 24 hour server that my community can use. I checked the setup parameters and see this "java -Xms6G -Xmx7G -jar server.jar" dunno if that helps at all

**Comment by PikaMug** [comment] 2019-11-24 08:53
That's alright, thank you again for trying. The setup parameters you mentioned just tell the server how much memory to use (in your case, between 6 and 7 gigabytes). If you're using Pterodactly Panel ([link](https://www.spigotmc.org/threads/pterodactyl-panel-%E2%80%94-the-next-generation-of-free-multi-server-management-now-with-whmcs-support.114030/)) it's most likely that you're running Java 8.

**Comment by MrRayhonda** [comment] 2019-11-24 09:28
Oh okay cool! I'm glad we could figure that out. That is what I'm using it seems. I didn't set it up but the screen shots match the website back end

**Comment by PikaMug** [comment] 2020-02-18 06:22
I've tried several times to replicate this bug, but without any luck. Since the trail has gone cold, I'm closing this in order to focus effort on the original issue. Please direct further input to #993

**Closed by PikaMug** 2020-02-18 06:22 UTC
Labels: bug, duplicate
