### ISSUE TITLE
New option as it Was. Deny msg first.

### ISSUE THREAD

**Issue by Danrique** [PikaMug/Quests#1468] opened 2020-11-20 23:33 UTC
Hi thanks for the plugin in first place!

I noticed that something changed from previews versions.

**It was:** If you did not met the requirment, you receive the requirments or a custom message that you make.

**Now:** First the npc ask the question if you want the mission regardless if you met the requirments. If you dont have what is nedded you then receive the requirments or the custom msg.

Well, thats a big change for the lore of the messages, I myself will have to rewrite 100 quests to not appear "bugged". Another user related in discord that he will have to do that with over 800 quests... I am sure thare is a lot of ppl that will have this problem.

I am using the option "ignore-locked-quests: true" to not even show the quests that you cant do now, but for me is important that ppl know where are the quests are the first visit of the place so in the future, when they are qualify to do, they already know where they should go. 

Another problem with this option is that I use some npcs for information, so I make a quest that rerquire a permission than nobody have and the negative custom message for not met the requirments are the messege I want to send to the player. **It works like a info npc that you can ask several things.** 

My suggestion then Is add an option to config to allow the plugin works as it was. I dont recomend change back because some ppl already changed the lore msgs and this will make they have to work again...

This is possible please?

Ah english is not my main lenguage, I hope I made my point clear enough.

**Comment by PikaMug** [comment] 2020-11-21 07:42
Thanks for the suggestion, but I am having trouble understanding what it is you're asking. Could you please make a second attempt at explaining?

**Comment by Danrique** [comment] 2020-11-21 19:38
Sure...

I want to show the negative messege that you dont have the requisits first if you dont have the requirments than show the question messege asking if you want to do the mission.

It was that way in previeus versions. Now It always asks if you want to do the mission and then if you dont have the requirements it shows the messege that you dont have.

Hope you get it =D

**Comment by PikaMug** [comment] 2020-11-21 21:18
Pretty sure you just want to set `ask-confirmation: false` in your _config.yml_ file?

**Comment by Danrique** [comment] 2020-11-22 00:45
No...

How it is working right now:

1 - Always make the question to the person if they want to do the mission. Its ok I want this, the person says yes or no.

2 - If you have all requirments the quest start. This part is ok.

3 - If you dont have the requirments, the requirments are displayed or you can customize the messege.

The order was 3 then 1 then 2. Now is 1 then 2 then 3.

This makes a huge difference as I stated in the orignal post...

get it?

**Comment by PikaMug** [comment] 2020-11-23 03:08
So you want Requirements to be checked before the Yes/No confirmation? If so, this may be a duplicate of #1259 albeit for a different reason. That issue is from April, so you must be updating from a very old version. Since setting `ask-confirmation: false` will essentially remove your step 1, I don't really see a need for a new config option.

**Closed by PikaMug** 2020-11-23 03:08 UTC
Labels: enhancement

**Comment by Danrique** [comment] 2020-11-24 04:23
Thats true, I keep the same version if there is no problem. For experience, if its ok, dont touch.

The problem is the lore of the missions, me and other users already writed all to work that way. With this new way the lore of the quests, once fine, now looks buggy...
