### ISSUE TITLE
Allow multiple custom objectives set per stage

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1643] opened 2021-03-13 23:36 UTC
**What does your feature do?**
We can already set multiple objectives per a single stage (1 per type of objective)
I just want us to be able to set multiple objectives of the same type per stage, such as custom objectives, as well as setting multiple objectives of the same type per stage.

**How would people use it?**
You could set like 5 types of blocks to mine in one stage, and smelt all 5 of them in one stage, or you could set 5 custom objectives in one stage.

**Comment by PikaMug** [comment] 2021-03-14 00:58
Duplicate of #789

**Closed by PikaMug** 2021-03-14 00:58 UTC
Labels: enhancement
