### ISSUE TITLE
Multi outcome quests for npcs

### ISSUE THREAD

**Issue by majster2nn** [PikaMug/Quests#2162] opened 2023-11-15 21:51 UTC
### What does your feature do?

This new feature would add the decision option for quests that would lead to different paths in quests etc

### How would people use it?

To create different paths adding immersion to quests

**Comment by PikaMug** [comment] 2023-11-15 22:27
Duplicate of #454

**Closed by PikaMug** 2023-11-15 22:27 UTC
Labels: enhancement

**Comment by majster2nn** [comment] 2023-11-16 16:42
i meant it for npcs in citizen 2 forgot to add that anyway

**Comment by majster2nn** [comment] 2023-11-16 16:47
and its not even quite multi otcomes cuz you dont make the decision you just complete quest and it blocks other
