### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by davsla12** [PikaMug/Quests#2128] opened 2023-06-20 03:17 UTC
### Where else have you looked for answers to this question?

I looket to documentation

### Share your question with as much detail as possible.

I installed vault but it says not installed

**Comment by PikaMug** [comment] 2023-06-20 03:19
Duplicate of #2126 

As mentioned in previous issue, you need an economy plugin, as well.

**Closed by PikaMug** 2023-06-20 03:19 UTC
Labels: question

**Comment by davsla12** [comment] 2023-06-20 03:45
Which economic plugin?

**Comment by PikaMug** [comment] 2023-06-20 03:46
@davsla12 Any that are compatible with Vault. For example, https://www.spigotmc.org/resources/fe.723/
