### ISSUE TITLE
Error when trying to place a location

### ISSUE THREAD

**Issue by tagelis** [PikaMug/Quests#2223] opened 2024-06-07 14:52 UTC
### What is your Quests version / build number (do *not* say "latest")?

5.0.2

### Describe the problem and how to replicate it.

When I hit option 1 to get to a location, nothing happens and the error occurs in the console. Basically it does not let me place the location I want. I don't even get the option to right click on the location I want. Thanks!
![error](https://github.com/PikaMug/Quests/assets/59883251/9429d995-f28a-480a-b1e7-61cab71731ea)

### Any console errors to share?

```shell
[14:39:45 WARN]: [Quests] Plugin Quests v5.0.2-b469 generated an exception whilst handling conversation input
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
        at me.pikamug.quests.convo.quests.stages.QuestStageMainPrompt$QuestReachListPrompt.acceptValidatedInput(QuestStageMainPrompt.java:755) ~[Quests-5.0.2.jar:?]
        at org.bukkit.conversations.NumericPrompt.acceptValidatedInput(NumericPrompt.java:37) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.conversations.ValidatingPrompt.acceptInput(ValidatingPrompt.java:30) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) ~[pufferfish-1.20.2.jar:git-Pufferfish-35]
        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:2272) ~[pufferfish-1.20.2.jar:git-Pufferfish-35]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$2.run(ServerGamePacketListenerImpl.java:2438) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[pufferfish-1.20.2.jar:git-Pufferfish-35]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.20.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1381) ~[pufferfish-1.20.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1158) ~[pufferfish-1.20.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[pufferfish-1.20.2.jar:git-Pufferfish-35]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by PikaMug** [comment] 2024-06-07 20:27
Duplicate of #2217 

Please try the [latest dev build](https://ci.codemc.io/job/PikaMug/job/Quests/) and if you have any trouble, reply to that issue. Thanks!

**Closed by PikaMug** 2024-06-07 20:27 UTC
Labels: bug
