### ISSUE TITLE
Can't start a quest with GUI item (3.7.6)

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#865] opened 2019-07-24 10:12 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

Quests 3.7.6
Server 1.8.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
-- Problem 1 --

Just ... can't pick a quest with a Gui Item (when clicking on it, nothing happen)
However, the questadmin give (quest) works for the quest that you can't start with the GUI item

-- Problem 2 --

Same as 3.7.5. Event 1 called twice.
First on the first stage, and another one on the second stage (You already know the problem)

I've seen "Run Action timers synchronously" as a bug fix into the update of the 3.7.6 (that's why i post it there again! ;)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Every quests.

**Comment by PikaMug** [comment] 2019-07-26 03:24
Going forward, please do not join multiple problems into a single ticket. Create one issue per problem.

Problem 1: Unable to replicate. Please provide at least one quest for testing via Pastebin/Hastebin. Also, please post the contents of your gui.yml file.

Problem 2: Sounds like a duplicate of #838

**Comment by tiradorus** [comment] 2019-07-26 13:34
Yeah i know about 1 problem per tickets, but the second one ... is a problem that you already know.
I just wanted to told you that the problem 2 isn't solved even with the new version ;)
(And the problem 2 is so important that every versions of quests who have this problem are unusable, it should be the most important thing to fix)

For the problem 1 ... eeeehhh ... for pasteBin it should be hard for me actually, i just have updated my version from 3.6.8 to 3.7.6 for testing it.
When i update from 3.6.8 to 3.7.5, GUI works
When i udpate from 3.6.8 to 3.7.6, GUI don't works. That's all. And this for every quest.

But however, my server is open, and i can't stop everything and expulse everyone just to update on a bugged version of quest, to just take a config and paste it there. 
And when i update from 3.6.8 to 3.7.5 or 3.7.6, all of the Events are named Actions, so when i downgrade it from 3.76 to 3.6.8, all of my quests have no Events anymore i have to do a total rollback of quests...

If you really need a pastebin okay i can do it ... but tell me in advance, i have to explain it to my community.
And if you want to replicate the problem, create a quest with the 3.6.8's version, update to 3.7.6 and test your Events, and your GUI item .. (i'm on 1.8.8 so if you wanna try it, maybe the 1.8.8 have a different behavior, i don't know) 

... i have more than 180 quests on the server "1", i can't do a manual modification of each quest because of a strange update ... 
And i have more than 500 quests on all of my servers so ... if i have to update quests somewhere, i have to update evrywhere. I just can't do it manually for each servers ...

Ps: I need the "\n" to end my server's update and i just can't because of thoses 2 bugs ... Gui and Events.
All is suspended. I've ended all others features of the upgrade, i just need a stable version of quests with the \n enabled.
Hundreds of players are waiting for it ... and i'm waiting too :/
Have a nice day!

**Closed** 2019-07-26 19:53 UTC

**Comment by PikaMug** [comment] 2019-07-26 20:25
Use https://ci.codemc.org/job/PikaMug/job/Quests/11/
