### ISSUE TITLE
Quests got Reset

### ISSUE THREAD

**Issue by Andore97** [PikaMug/Quests#1260] opened 2020-04-27 11:32 UTC
The Quests get randomly reset from players
Paperspigot 1.8.8 R0.1
Quests 3.9.3-b107

A Quest looks like this:
https://pastebin.com/dHcaCDdB

And this Errors comes with the Reset.

`[13:21:19 ERROR]: Could not pass event PlayerMoveEvent to Quests v3.9.3-b107
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_212]
        at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_212]
        at me.blackvein.quests.Quester.getCurrentObjectives(Quester.java:1025) ~[?:?]
        at me.blackvein.quests.Quester.updateJournal(Quester.java:406) ~[?:?]
        at me.blackvein.quests.Quester$1.put(Quester.java:90) ~[?:?]
        at me.blackvein.quests.Quester$1.put(Quester.java:83) ~[?:?]
        at me.blackvein.quests.Quester.loadData(Quester.java:3037) ~[?:?]
        at me.blackvein.quests.Quests.getQuester(Quests.java:1243) ~[?:?]
        at me.blackvein.quests.listeners.PlayerListener.playerMove(PlayerListener.java:1067) ~[?:?]
        at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:1056) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 16 more
`
**Please add MySQL or SQL Support.**

**Comment by PikaMug** [comment] 2020-04-27 20:26
Duplicate of #1233 

Use https://ci.codemc.io/job/PikaMug/job/Quests/116/

**Closed by PikaMug** 2020-04-27 20:26 UTC
Labels: bug
