### ISSUE TITLE
Console spam - Errors

### ISSUE THREAD

**Issue by Ewokens** [PikaMug/Quests#2236] opened 2024-06-26 18:41 UTC
### What is your Quests version / build number (do *not* say "latest")?

5.0.5

### Describe the problem and how to replicate it.

Just start the server up and the console starts to spam the below console error.

### Any console errors to share?

```shell
26.06 18:40:27 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
26.06 18:40:27 [Server] ERROR Could not pass event PlayerInteractEvent to Quests v5.0.5-b478
26.06 18:40:27 [Server] INFO java.lang.IllegalArgumentException: amount must be greater than 0
26.06 18:40:27 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
26.06 18:40:27 [Server] INFO at org.bukkit.inventory.ItemStack.of(ItemStack.java:59) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
26.06 18:40:27 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
26.06 18:40:27 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
26.06 18:40:27 [Server] INFO at org.bukkit.material.MaterialData.toItemStack(MaterialData.java:72) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
26.06 18:40:27 [Server] INFO at Quests-5.0.5.jar/me.pikamug.quests.listeners.BukkitBlockListener.onBlockUse(BukkitBlockListener.java:340) ~[Quests-5.0.5.jar:?]
26.06 18:40:27 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor303.execute(Unknown Source) ~[?:?]
26.06 18:40:27 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
26.06 18:40:27 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
26.06 18:40:27 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
26.06 18:40:27 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1871) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-37-dd49fba]
26.06 18:40:27 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Default Quest File no quest have been created.
```

**Comment by Ewokens** [comment] 2024-06-26 18:51
Please note I use the following release that was supposed to fix the error I believe... 5.0.5

**Comment by PikaMug** [comment] 2024-06-26 18:56
Duplicate of #2235 

Again, see #2233 this has already been resolved with a development build.

**Comment by PikaMug** [comment] 2024-06-26 18:58
Sorry, I've just noticed you're using build 478. I'll look into this shortly.

**Comment by Ewokens** [comment] 2024-06-26 19:08
Thank you and yes I followed your instruction I should be more clear I do apologize 

- https://ci.codemc.io/job/PikaMug/job/Quests/478/

**Comment by PikaMug** [comment] 2024-06-27 20:30
Still looking into this. Can I see the output of your `/version` command?

**Comment by JKRohlfing** [comment] 2024-06-28 22:06
This server is running Paper version 1.21-38-master@1f5db50 (2024-06-27T20:15:58Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-37-dd49fba (MC: 1.21)

**Comment by shantek** [comment] 2024-06-29 05:51
Also seeing the same issue here for a quest that used to work. Same paper version

**Closed** 2024-06-30 04:46 UTC
Labels: bug, duplicate

**Comment by PikaMug** [comment] 2024-06-30 04:51
Unfortunately, a breaking change seen in recent builds of Paper are the cause. Similar to #2233 I've created a workaround which may introduce side-effects. Please give https://ci.codemc.io/job/PikaMug/job/Quests/479/ a try, and report any bugs in a new ticket. Thanks!
