### ISSUE TITLE
Error "Cannot measure distance"

### ISSUE THREAD

**Issue by PappoYT** [PikaMug/Quests#1725] opened 2021-06-20 08:23 UTC
Paper version git-Paper-772 (MC: 1.16.5)
Quests-4.0.4.jar

Log: [https://mclo.gs/C6Fkyv8](https://mclo.gs/C6Fkyv8)
Quests.yml: [https://pastebin.com/rHQheeB](https://pastebin.com/rHQheeB)

I found several errors like this in console:
```
[07:50:40] [Server thread/ERROR]:&nbsp;[Quests] An error has occurred with Quests. Please report on Github with info below
66028 | [07:50:40] [Server thread/WARN]:&nbsp;[Quests] quest = custom15
66029 | [07:50:40] [Server thread/WARN]:&nbsp;[Quests] index = 0
66030 | [07:50:40] [Server thread/WARN]:&nbsp;[Quests] location = Location{world=CraftWorld{name=world_vanillaiscritti_the_end},x=-81.8209099151521,y=2.0,z=217.95699883009945,pitch=6.490556,yaw=571.2251}
66031 | [07:50:40] [Server thread/WARN]:&nbsp;[Quests] locationsToReach = 1
66032 | [07:50:40] [Server thread/WARN]:&nbsp;[Quests] locationsReached = 1
66033 | [07:50:40] [Server thread/WARN]:&nbsp;[Quests] hasReached = 1
66034 | [07:50:40] [Server thread/WARN]:&nbsp;java.lang.IllegalArgumentException: Cannot measure distance between world_vanillaiscritti and world_vanillaiscritti_the_end
66035 | [07:50:40] [Server thread/WARN]:&nbsp;at org.bukkit.Location.distanceSquared(Location.java:510)
66036 | [07:50:40] [Server thread/WARN]:&nbsp;at me.blackvein.quests.Quester.reachLocation(Quester.java:2583)
66037 | [07:50:40] [Server thread/WARN]:&nbsp;at me.blackvein.quests.listeners.PlayerListener$4$1.run(PlayerListener.java:993)
66038 | [07:50:40] [Server thread/WARN]:&nbsp;at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
66039 | [07:50:40] [Server thread/WARN]:&nbsp;at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
66040 | [07:50:40] [Server thread/WARN]:&nbsp;at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427)
66041 | [07:50:40] [Server thread/WARN]:&nbsp;at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
66042 | [07:50:40] [Server thread/WARN]:&nbsp;at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
66043 | [07:50:40] [Server thread/WARN]:&nbsp;at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
66044 | [07:50:40] [Server thread/WARN]:&nbsp;at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
66045 | [07:50:40] [Server thread/WARN]:&nbsp;at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by PikaMug** [comment] 2021-06-20 10:03
Duplicate of #1709 

Use https://ci.codemc.io/job/PikaMug/job/Quests/246/

**Closed by PikaMug** 2021-06-20 10:03 UTC
Labels: bug
