### ISSUE TITLE
NPC Delivery Quests not working

### ISSUE THREAD

**Issue by Castiella** [PikaMug/Quests#1921] opened 2022-04-09 17:29 UTC
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.3.0-b320

[17:27:55 INFO]: This server is running Paper version git-Paper-278 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 62dcff3)

### Describe the problem and how to replicate it.

Since I updated, players are unable to complete NPC Delivery Quests. These worked fine before.

Error Message  "name x quantity is not a required item for this quest! the difference is 'name'."

### Any console errors to share?

```shell
No console output
```

**Comment by PikaMug** [comment] 2022-04-09 17:49
Duplicate of #1919

**Closed by PikaMug** 2022-04-09 17:49 UTC
Labels: bug
