### ISSUE TITLE
Quests progress got erased again (third time)

### ISSUE THREAD

**Issue by Grallow** [PikaMug/Quests#1769] opened 2021-08-11 12:39 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

4.0.5

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

A few months ago I noticed someone's progression got reset.
Like 2 hours ago it happened again, I used an old backup to restore their quest data since it reset completely and they were able to redo quests they've already done.
I made a post here, they said to get updated version of plugin, I did, then now someone just said they came back from lunch and their quests reset. Its happening more often now because we started getting players on the server. It could have been because I restarted the server to fix some other stuff? But im not sure what caused the problem.

Any suggestions on how to fix?

**Comment by DeadlykillOfficial** [comment] 2021-08-11 14:50
As I stated in discord this is a issue which has several opened cases. But nobody of us or anyone else wasn't able to replicate it, or provide actual cause of this happenings as it seems to be happening to random people.
Reasons could be hundreds. Most popular I can think of are lack of enough ram, since quests it's running on ram entirely to hash all the data.
It could be wring server stopping or force stopping. Could be some kind of Lag cleaner plugin, which in 99% of cases lag more the server or mess with other plugins. Depending on type of lag cleaner it could be some memory saving method that dump any exceesive data of memory which it thinks it could be useless and Therefor this is happening.
As I have said until actual reason what is the cause of all that, this issue is under investigation.

**Comment by PikaMug** [comment] 2021-09-06 02:56
Likely duplicate of #1707

**Closed by PikaMug** 2021-09-06 02:56 UTC
Labels: bug
