### ISSUE TITLE
Need a lil help 

### ISSUE THREAD

**Issue by AmazonOmega** [PikaMug/Quests#1423] opened 2020-10-15 02:02 UTC
https://pastebin.com/up97Wyf5

i would like to know if this is some sort of bug or if there is a fix for this?

Thanks!

**Comment by PikaMug** [comment] 2020-10-15 02:44
Duplicate of #1419. Use the latest development build at https://ci.codemc.io/job/PikaMug/job/Quests/153/

**Closed by PikaMug** 2020-10-15 02:44 UTC
Labels: bug
