### ISSUE TITLE
Anytime a quest is edited in any way it resets the resets the item rewards?

### ISSUE THREAD

**Issue by VirtualPixel** [PikaMug/Quests#891] opened 2019-08-02 23:24 UTC
**What is your Quests version / build number (do _not_ say "latest")?** 3.7.8-b16

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?** If you edit the quest in just about any way we've seen and you have an item reward upon completion of the quest, it gets rid of the item reward and needs to be added again. 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?** https://pastebin.com/8SdS9DPT

**Comment by PikaMug** [comment] 2019-08-03 05:25
Which quest are you testing with? I see several with item rewards.

When you say "get rid of" do you mean it no longer appears in the editor, or the player no longer receives the item?

**Comment by VirtualPixel** [comment] 2019-08-03 15:11
It's any custom quest we make. 

It's no longer in the editor and the player no longer receives the item upon completion.

**Comment by PikaMug** [comment] 2019-08-04 04:55
Duplicate of #888

@VirtualPixel Use https://ci.codemc.org/job/PikaMug/job/Quests/19/

**Warning:** The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it. Alternatively, wait until the final release on Spigot.

**Closed by PikaMug** 2019-08-04 04:55 UTC
Labels: bug, duplicate
