### ISSUE TITLE
Fix Denizen Bridge

### ISSUE THREAD

**Issue by Elxafil** [PikaMug/Quests#857] opened 2019-07-20 11:41 UTC
**What is your Quests version / build number (do _not_ say "latest")?** 3.7.5 (No Idea what exact build, latest one on official spigot site bc jenkins won't load)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**Basic startup log: https://pastebin.com/9uEQdcqD

**Comment by Elxafil** [comment] 2019-07-20 11:45
Can confirm same error on 3.7.6 build 2.

**Comment by PikaMug** [comment] 2019-07-20 16:25
What is your Denizen version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Elxafil** [comment] 2019-07-20 21:21
![image](https://user-images.githubusercontent.com/13818994/61584265-e4972480-ab98-11e9-83ad-3ff2b9b7c6f4.png)

**Comment by PikaMug** [comment] 2019-07-20 21:26
Duplicate of #845

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by PikaMug** 2019-07-20 21:26 UTC
