### ISSUE TITLE
Could not pass event EntityDeathEvent to Quests

### ISSUE THREAD

**Issue by MoguCraft** [PikaMug/Quests#899] opened 2019-08-05 19:55 UTC
My console gets this error, cant find the problem.
https://pastebin.com/DP8xmB4d

**Comment by PikaMug** [comment] 2019-08-06 00:03
Duplicate of #886 

@MoguCraft This has already been fixed. Use Quests 3.7.8

**Closed by PikaMug** 2019-08-06 00:03 UTC
